### ISSUE TITLE
Возможно мимо, но всё же: Обрезанные постеры на estuary с wall viewtype 

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#104]
Перешел на стандартный скин коди 18.X и обнаружил что при выборе wall как viewtype постеры фильмов итд обрезаны, что не совсем удобно :(.

В разделе "я смотрю" всё волшебно кстати с wall view.

Возможно к плагину отношения не имеет, но может кто сталкивался и решил проблему?

Заранее спасибо

[ТЫЦ](https://imgur.com/a/cU35LOJ)

EDIT 1:
в confluence скине вроде всё ок, но есть маразм...
я смотрю, сериалы, фильмы - показывают 2 ряда картинок на страницу (Thumbnails view)
а вот закладки, новинки и еше некоторые в 3 ряда, что делает картинки маленькими

Можно ли как-то сделать консистентно?

**Comment by quarckster** [comment]
Плагин не обрезает картинки, он просто передаёт ссылки на постеры в необходимые поля. Например https://github.com/quarckster/kodi.kino.pub/blob/master/src/resources/lib/modeling.py#L152 Всё отсальное делает Kodi.
