### ISSUE TITLE
Недосмотренные фильмы

### ISSUE THREAD

**Issue by olsamurai** [quarckster/kodi.kino.pub#11]
Было бы удобно, если по аналогии к Коди недосмотренные фильмы или показывались в самом верху списка или отдельная папка была.

**Comment by Kampfader** [comment]
не было бы лучше, сделать это https://github.com/quarckster/kodi.kino.pub/issues/4 и патом добавлять Фильмы, Сериалы в библиотеку от Коди, и остальное он сам будит делать, там уже как кто хочет, по настройкам..

**Comment by olsamurai** [comment]
Упорствовать в этом вопросе я не буду. Только на запрос: 
GET https://api.service-kp.com/v1/watching/movies
массив item в моем тесте всегда пустой был. Но я мог там накуралесить, т.к. на питоне я толком не пишу, а на С++ городить не охота.

**Comment by quarckster** [comment]
https://github.com/quarckster/kodi.kino.pub/commit/ab6a81fbf8b9bde10bc25c7a1c75b261e151d3f5
