### ISSUE TITLE
загрузки папок

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#117]
Последкий коммит "speed up" просто чуто в "я смотрю" 37 сериалов, пару секунд и загрузилось! Спасибо! супер!

Вопрос про закладки, там ограничение на 20 айтемов на странице, есть папка с 3мя, 4мя страницами, заходит в нее секунд 25, внутри след. страницу тоже секунд 25 где-то.

Возможно ли подкрутить?

Спасибо!

**Comment by quarckster** [comment]
Вряд ли тут что-то можно придумать, на каждый элемент списка нужно выполнить отдельный запрос к API, чтобы получить данные о просмотре.
