### ISSUE TITLE
Сортировка сериалов по названиям: переключение русское/оригинальное

### ISSUE THREAD

**Issue by apazhe** [quarckster/kodi.kino.pub#12]
Очень удобно было бы. Можно просто в настройках плагина.

**Comment by quarckster** [comment]
API кинопаба выдаёт оригинальные и переведённые названия в одной строке `Название / Title`. Я могу попробовать это реализовать, но пока не в приоритете.

**Comment by quarckster** [comment]
@apazhe где именно в сериалах должна быть реализована эта сортировка?

**Comment by apazhe** [comment]
Например, в «я смотрю».

А лучше везде. Я часто ищу сериал по оригинальному названию.

**Comment by quarckster** [comment]
Поиск и так ищет как по оригнальному, так и по локализованному названиям. А сортировка kodi не работает в плагине.
