### ISSUE TITLE
Перестали работать Трейлеры

### ISSUE THREAD

**Issue by Sheredeka** [quarckster/kodi.kino.pub#121]
Скачал "пре-релиз" (крайний коммит Moved status to TVShow (#119)) - все клёво, но в отличии от релиза 2.10.0 перестали работать трейлеры. (трейлер запускаю из сведений о видео).

Ошибки в логе коди:
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.routing.RoutingException'>
                                            Error Contents: No route to path "/trailer/65566"
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 76, in run
                                                self.routing.dispatch(self.path)
                                              File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 65, in dispatch
                                                raise RoutingException('No route to path "{}"'.format(path))
                                            RoutingException: No route to path "/trailer/65566"
                                            -->End of Python script error report<--
WARNING: CPythonInvoker(15, /storage/.kodi/addons/video.kino.pub/addon.py): the python script "/storage/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
`

Надеюсь это поможет избежать ее в новом релизе. Спасибо за ваш труд!

**Comment by quarckster** [comment]
Спасибо за тестирование. Исправлю баг.
