### ISSUE TITLE
[Возможно баг не аддона, а kodi] Не запоминает выбранную озвучку при переключении эпизодов + нет отметок о просмотре

### ISSUE THREAD

**Issue by Krishnacore** [quarckster/kodi.kino.pub#129]
Kodi 18.8 на XBOX One S
Собственно, вся суть и описана. Иногда запоминает и воспроизводится та же дорожка, но чаще - первая в списке. Так же нет отметок о том, что эпизод просмотрен или наоборот все вдруг отображаются просмотренными, часто не сохранятсе момент, гдн остановился, если эпизод или фильм не был досмотрен. Не уверен, это аддон или сам kodi.

**Comment by quarckster** [comment]
Это "багофича" коди.
