### ISSUE TITLE
Возможно ли автоматически включать следующию серию? 

### ISSUE THREAD

**Issue by allmazz** [quarckster/kodi.kino.pub#130]
Здравствуйте. Возможно ли автоматически включать следующие серию при просмотре сериала? Очень напрягает каждый раз вручную включать.

**Comment by quarckster** [comment]
Для этого надо прочитать мануал Kodi. Settings->Video->Playback - Play next
video automatically

пн, 14 сент. 2020 г., 16:57 allmaZz <notifications@github.com>:
