### ISSUE TITLE
Ошибка 502

### ISSUE THREAD

**Issue by Sheredeka** [quarckster/kodi.kino.pub#132]
Второй день вылетает ошибка 502 при переходе в Горячие / Популярные / Последние. В общем при любых движениях по каталогу...
Лог прицепил.

CoreELEC (official): 9.2.4.2 (Amlogic-ng.arm)
name="kino.pub" version="2.12.1"
[log.txt](https://github.com/quarckster/kodi.kino.pub/files/5329782/log.txt)

**Comment by stavultras** [comment]
Сервер Россия? У меня вчера такое было, переключился на другой, ошибка исчезла.

**Comment by Sheredeka** [comment]
Да и у меня было вчера пару раз, но потом вроде все стабилизировалось.
Переключил на Германию - проблема не ушла.
Судя вылету "Хьюстон у нас проблемы" на сайте кинопаба - думаю это на их стороне засада. Подождем пока решат.

**Comment by quarckster** [comment]
Проблема на сервере кинопаба.
