### ISSUE TITLE
Нельзя выбрать звуковую дорожку, кроме русской

### ISSUE THREAD

**Issue by kolnogorov** [quarckster/kodi.kino.pub#141]
**Describe the bug**
В настройках аудио показывается, что у всех фильмов и сериалов только одна звуковая дорожка, и нельзя выбрать другую (хотя на самом деле их может быть несколько).

**To Reproduce**
1. Открыть любой фильм или сериал.
2. Выбать "Audio settings"
3. Пункт Audio stream будет неактивным, и возможности выбрать и переключить дорожку не будет.

**Actual results**
Ничего не происходит.

**Expected behavior**
Должны отображаться все звуковые дорожки фильма и должна быть возможность их выбрать.

**Screenshots**
![image](https://user-images.githubusercontent.com/8288103/95685028-0a757280-0bfe-11eb-8276-eca3b2346016.png)

**Additional context**
Устройство Raspberry PI, Kodi под OSMC.

Версия плагина: 2.12.3.
Версия Kodi: 18.7.

**Comment by quarckster** [comment]
Проверьте тип стриминга в настройках. HTTP и HLS4 позволяют выбирать дорожки.

**Comment by AlexParamonov** [comment]
Не работает на последнем стабильном билде kodi 18.9 и плагине для него 2.12.4

Потоки hls4 и http пробовал. Amazon Fire TV 4K.

**Comment by AlexParamonov** [comment]
Оказывается менять настройки потока нужно в самом приложении, а не на сайте
