### ISSUE TITLE
В поиске выдаёт только непросмотренные фильмы 

### ISSUE THREAD

**Issue by vhsdc** [quarckster/kodi.kino.pub#144]
В поиске выдаёт только непросмотренные фильмы. В левом верхнем углу пишет kino.pub: Unwached. 
Непонятно как от этого избавится.

**Comment by quarckster** [comment]
Скорее всего у вас фильтр настроен в kodi, плагин тут ни при чём.

**Comment by vhsdc** [comment]
Да, вы правы. Спасибо. Я уже исправил.


Sent from Yahoo Mail for iPhone


On Sunday, November 22, 2020, 3:32 PM, Dmitrii Misharov <notifications@github.com> wrote:




Скорее всего у вас фильтр настроен в kodi, плагин тут ни при чём.
