### ISSUE TITLE
Kodi, Orang Pi, H3

### ISSUE THREAD

**Issue by buyfishya** [quarckster/kodi.kino.pub#146]
1)Подскажите на одноплатном Orange Pi (H3) какой тип потока лучше выбирать HTTP, HLS, HLS2? HLS4(не работает).
2)При включении HLS, HLS2 обязательно ли надо включать input stream adaptive ?
3)на сайте надо ли синхронно выставлять тип потока аналогично плееру? Если да, то на сайте нет HLS, а только HTTP, HLS2, HLS4?

**Comment by quarckster** [comment]
1) HLS4 предпочтительней и это не зависит от железа
2) Для hls inputstream adaptive необходим
3) Настройки на сайте влияют только на расположение серверов

**Comment by buyfishya** [comment]
1. HLS4  не работает, картинки нет, что-то с железом. На HLS2 работает почти все, но бывают редко проблемы. Переключаюсь тогда на HLS и если не помогает меняю сервер вещания. Вот и думаю может изначально что-то не так делаю. HLS2 тоже не верно. 
2. Получается для любого HLS необходим inputstream adaptive ?
3. HLS как то влияет на полосу пропускания? на Raspberry у меня HLS4 нормально работает. И лишь совсем изредка иногда все таки ставлю другой тип потока, и странно но это помогает... 
4. сейчас решил везде последние версии плагина поставить 2.12.4 и понаблюдать.

**Comment by buyfishya** [comment]
> 1. HLS4 предпочтительней и это не зависит от железа
> 2. Для hls inputstream adaptive необходим
> 3. Настройки на сайте не влияют только на расположение серверов

?

**Comment by buyfishya** [comment]
- author@ HLS4 не работает, картинки нет, что-то с железом. На HLS2 работает почти все, но бывают редко проблемы. Переключаюсь тогда на HLS и если не помогает меняю сервер вещания. Вот и думаю может изначально что-то не так делаю. HLS2 тоже не верно.Получается для любого HLS необходим inputstream adaptive ? А что будет если его не установить?HLS как то влияет на полосу пропускания? на Raspberry у меня HLS4 нормально работает. И лишь совсем изредка иногда все таки ставлю другой тип потока, и странно но это помогает...сейчас решил везде последние версии плагина поставить 2.12.4 и понаблюдать. 30.11.2020, 23:06, "Dmitrii Misharov" <notifications@github.com>: HLS4 предпочтительней и это не зависит от железаДля hls inputstream adaptive необходимНастройки на сайте не влияют только на расположение серверов—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
