### ISSUE TITLE
Проблемы с разделом "Недосмотренные"

### ISSUE THREAD

**Issue by olsamurai** [quarckster/kodi.kino.pub#15]
1. Начатых к просмотру в закладках 11 фильмов. В разделе "Недосмотренные" отображаются только 4 из всех.

2. В разделе"Недосмотренные" фильмы отображаются так, как не начатые к просмотру и воспроизведение начинается с начала фильма, а не с места, где остановился.

**Comment by quarckster** [comment]
В разделе "Недосмотренные" показывается только те фильмы, что выдаются через API как недосмотренные. Скорее всего другие 7 видео отображаются как недосмотренные только в коди.
Что касается второго пункта, то я попробовал решить проблему в 2.1.6

**Comment by olsamurai** [comment]
Честно говоря мне очень нравится версия 2.1.4. Очень стабильная и предсказуемая. Может имеет смысл в версию 2.1.4 закоммитить фиксы из 2.1.5 и 2.1.6 beta1? А раздел Недосмотренные вообще выпилить?

**Comment by quarckster** [comment]
Ещё один подход в 2.1.6.beta2.

**Comment by olsamurai** [comment]
Похоже всё работает как надо!
