### ISSUE TITLE
kino.pub 3.0.1 failed to install

### ISSUE THREAD

**Issue by vhsdc** [quarckster/kodi.kino.pub#152]
Kodi выдает сообщение, dependecy on xbmc.com python version 3.0.0 could not be satisfied 
и инсталляция не производится. Предыдущая версия 2.13. инсталлировалась и  работала без проблем

**Comment by quarckster** [comment]
Пожалуйста прочитайте README и примечания к релизу.

**Comment by vhsdc** [comment]
Спасибо. Моя вина - инсталлировал не прочитавши. А как теперь отогнать назад на предыдущую версию? 


Sent from Yahoo Mail for iPhone


On Monday, December 28, 2020, 2:02 AM, Dmitrii Misharov <notifications@github.com> wrote:




Пожалуйста прочитайте README и примечания к релизу.

**Comment by vhsdc** [comment]
Спасибо. Уже нашёл 2.12.4 версию.Извините за беспокойство.


Sent from Yahoo Mail for iPhone


On Monday, December 28, 2020, 10:46 AM, E K <drakon_1@yahoo.com> wrote:

Спасибо. Моя вина - инсталлировал не прочитавши. А как теперь отогнать назад на предыдущую версию? 


Sent from Yahoo Mail for iPhone


On Monday, December 28, 2020, 2:02 AM, Dmitrii Misharov <notifications@github.com> wrote:




Пожалуйста прочитайте README и примечания к релизу.
