### ISSUE TITLE
Не работает проигрывание с места остановки

### ISSUE THREAD

**Issue by olsamurai** [quarckster/kodi.kino.pub#16]
Вначале благодарочка за то, что selected item in listbox остаётся на месте, а не прыгает в начало страницы.
При проигрывании уже начатого к просмотру фильма (с сериалами всё в порядке) спрашивает как положено проиграть с, к примеру, 50-ой минуты? Выбираешь да, но проигрывает всё равно с начала...

**Comment by quarckster** [comment]
Попробовал исправить это в 2.1.6, только теперь не работает пункт контекстного меню "Start from the beginning". Непонятно это баг в аддоне или в kodi.

**Comment by olsamurai** [comment]
Пункт не работает и у меня.

Кроме того в закладках все фильмы отображаются как непросмотренные или же недосмотренные. Просмотренных вообще как будто нет. Откатываюсь на 2.1.4 и все становится на свои места. С сериалами всё корректно.

**Comment by olsamurai** [comment]
Маленькое дополнение: в версии 2.1.4 пункт "Start from the beginning" работает корректно.

**Comment by quarckster** [comment]
В 2.1.6.beta2 должно работать как "Resume from ..." так и "Play from beginning"

**Comment by olsamurai** [comment]
1. Работает проигрывание сначала и с места остановки. Класс!

2. "Selected item" во второй бэте опять теряется и после обновления списка курсор прыгает на верх.
