### ISSUE TITLE
Не работает выбор аудиодорожки на Google TV

### ISSUE THREAD

**Issue by xvonabur** [quarckster/kodi.kino.pub#182]
**Describe the bug**
На последнем Kodi 19 из Play Store и текущей версии плагина не работает выбор аудио дорожки. Пробовал все режимы от http до hls4. Во всех случаях в меню доступна только одна дорожка. Пробовал на 3м и 2м сезоне сериала The Crown. При этом в вэбэ выбор дорожки есть.

**To Reproduce**
Как воспроизвести:
1. Найти сериал The Crown (Корона) через данное дополнение к Kodi;
2. Выбрать 1ю серию 3го сезона;
3. Войти в меню выбора дорожек.

**Actual results**
В зависимости от режима (http, hls2, hls4) пункт меню со звуковой дорожкой будет содержать либо один вариант, либо вообще будет неактивным (серым).

**Expected behavior**
Должен быть доступен выбор всех дорожек у серии.

На Google TV из коробки нет поддержки AC3 кодека, хотя файлы с такой дорожкой из локальной сети Kodi проигрывает без проблем.
Готов собрать и предоставить логи. Скажите только какие.

**Comment by quarckster** [comment]
На моём Kodi, установленным на Linux, выбор дорожки. Плагин не влияет на количество дорожек, он только вытаскивает ссылку через API. Остальное всё на Kodi.

![screenshot_20210307_191222](https://user-images.githubusercontent.com/1011257/110249953-239a0980-7f79-11eb-8538-441f399f6031.png)

**Comment by maxdanilov** [comment]
У меня такая же проблема: на Android TV 9, Kodi 19 всегда показывается только одна дорожка, независимо от формата.

Очень похоже, что это всегда первая в списке дорожек в видео.

Этот баг точно не связан с плагином kino.pub?

**Comment by xvonabur** [comment]
@maxdanilov да. В моем случае оказалось, что kodi не сохранил переключение режима работы с hls на http. Дорожки грузятся только в режиме http.

**Comment by quarckster** [comment]
Выбор дорожек должен работать в http и hls4

**Comment by xvonabur** [comment]
@quarckster Пробовал все режимы на Google TV. Дорожки показываются только в режиме http. В любых hls, на примере выше, доступна только одна. На других ОС не пробовал.

**Comment by quarckster** [comment]
Установлен ли у вас inputstream.adaptive https://github.com/xbmc/inputstream.adaptive?

**Comment by xvonabur** [comment]
Да, установил сразу, как предложил плагин. Плагин не ругается, что inputstream.adaptive не установлен.

**Comment by quarckster** [comment]
Установил себе на телефон Kodi, плагин и inputstream.adaptive. Включил inputstream.adaptive и выбрал hls4. Дороги показываются:
![Screenshot_20210315-084641](https://user-images.githubusercontent.com/1011257/111120387-90aa3200-856b-11eb-9116-1b85d69cf5e9.png)

**Comment by quarckster** [comment]
Для андроида лучше всё-таки приложение использовать от кинопаба.

**Comment by maxdanilov** [comment]
не знал, что у кинопаба свое приложение под Андроид (https://kino.pub/plugin/android) - с ним действительно удобнее, чем с Kodi, все дорожки работают.

**Comment by xvonabur** [comment]
@quarckster Google выпилил поддержку AC3 кодека в Google TV. Так что если в видео есть такая дорожка, то отдельное приложение кнопаба ее не проиграет. Для Google TV выбор, к сожалению, только один.
