### ISSUE TITLE
Не работает на XBian с версией Python 3.7

### ISSUE THREAD

**Issue by sonnydbb** [quarckster/kodi.kino.pub#183]
Аддон не запускается под XBian. В логе ошибка: Cannot import name 'cached_property' from 'functools'.

cached_property появилась только в версии Python 3.8.

**Comment by quarckster** [comment]
На какой версии Kodi запускаете плагин?

**Comment by sonnydbb** [comment]
> На какой версии Kodi запускаете плагин?

Я видел ваш комментарий, что с версиями раньше 19 не совместимо.
Starting Kodi (19.0 (19.0.0) Git:20210311-735f685331-dirty). Platform: Linux ARM 32-bit
2021-03-13 17:57:46.191 T:2902     INFO <general>: Using Debug Kodi x32 build (version for Raspberry Pi)
2021-03-13 17:57:46.191 T:2902     INFO <general>: Kodi compiled 2021-03-11 by GCC 8.3.0 for Linux ARM 32-bit version 4.19.20 (267028)
2021-03-13 17:57:46.191 T:2902     INFO <general>: Running on BCM2835 with XBian 1.0 (knockout), kernel: Linux ARM 32-bit version 5.4.100+

**Comment by quarckster** [comment]
Интересно, как на Xbian собирают Kodi. Вроде как версия питона должна быть 3.8 https://github.com/xbmc/xbmc/blob/Matrix/CMakeLists.txt#L181

**Comment by sonnydbb** [comment]
Брал стандартный дистрибутив отсюда: https://sourceforge.net/projects/xbian/
А нельзя ли починить плагин, чтобы был совместим с 3.7?

**Comment by quarckster** [comment]
@sonnydbb да, обязательно починю.

**Comment by sonnydbb** [comment]
Спасибо большое, ждем. (Апгрейднуть питон на XBian после трех часов мучений моими кривыми руками не вышло, а сносить xbian и начинать эксперимент с другой коди-сборкой очень не хочется).

**Comment by quarckster** [comment]
Не могли бы вы протестировать эту версию плагина [video.kino.pub-3.0.3-beta1.zip](https://github.com/quarckster/kodi.kino.pub/files/6167292/video.kino.pub-3.0.3-beta1.zip)? Я сделал PR #186, если у вас заработает, тогда сделаю новый релиз.

**Comment by sonnydbb** [comment]
Заработало!
Все прекрасно, только главная функция не работает – Toggle audio stream.
Дорожка с русской не переключается (проверил на фильме, в котором точно есть оригинальная, с десктопа проигрывается).

**Comment by sonnydbb** [comment]
По клику на этот пункт меню вообще ничего не происходит.

**Comment by quarckster** [comment]
Это не проблема плагина.
