### ISSUE TITLE
Не могу установить новую версию плагина для Kodi 19

### ISSUE THREAD

**Issue by azakordonets** [quarckster/kodi.kino.pub#184]
**Describe the bug**
Моя версия Коди автоматически обновилась и kino.pub плагин перестал работать. Пытался установить новый плагин, но при установке получаю окно где говорится что два модуля должны будут еще дополнительно установиться ( script.module.inputstreamhelper & script.module.m3u8). Когда соглашаюсь с установкой, получаю ошибку - "The dependecy on script.module.m3u8 version 0.5.4 could not be satisfied)

**Additional context**
Kodi 19.0.0

**Comment by quarckster** [comment]
У вас должен быть включён стандартный репозиторий Kodi, оттуда должен установиться модуль m3u8 https://kodi.wiki/view/Add-on:M3u8 https://mirrors.kodi.tv/addons/matrix/script.module.m3u8/

**Comment by quarckster** [comment]
Была похожая проблема раньше, но я её починил. Вот здесь говорят, что всё работает https://github.com/quarckster/kodi.kino.pub/discussions/158#discussioncomment-321277

**Comment by azakordonets** [comment]
Каким то чудесным образом заработало :)
