### ISSUE TITLE
Kinopub

### ISSUE THREAD

**Issue by vadim33333** [quarckster/kodi.kino.pub#185]
Привет у меня kodi18.9 установлен Xbox one x где найти скрипт kino pub для него и какие варианты загрузок есть, только zip? или что то ещё?) Заранее спасибо)

**Comment by quarckster** [comment]
Пожалуйста вопросы задавайт на форуме https://github.com/quarckster/kodi.kino.pub/discussions. Плагины в Kodi распространяются только в zip архивах. Информация по установке https://kino.pub/plugin/kodiю
