### ISSUE TITLE
Не найден xbmc.python

### ISSUE THREAD

**Issue by Dimasua** [quarckster/kodi.kino.pub#188]
Установливаю на kodi (19)  плагин из zip-архива. Инсталятор ругается на отсутствие xbmc.python. Куда смотреть?

**Comment by quarckster** [comment]
Другие плагины работают в вашем Kodi?

**Comment by Dimasua** [comment]
У меня нет других плагинов, ставил kodi только для kinopub, потому что
плагин под dune перестал внезапно работать.

**Comment by quarckster** [comment]
Скорее всего проблема в вашем экземпляре Kodi, отстутствие `xbmc.python` означает, что Kodi не может найти Python интерпертатор в системе или сборка Kodi сломана.

**Comment by Dimasua** [comment]
Вот так выглядит сообщение.

"The dependency on xbmc.python 3.0.0 could not be satisfied."

Может python таки есть, но чего-то не хватает?

С официальных сайтов все скачивал, по ссылкам, которые указаны на сайте
kinopub. Также устанавливал две разные оболочки для kodi и во всех один и
тот же результат с xbmc.python.

**Comment by quarckster** [comment]
Kodi 19 требует именно эту версию https://kodi.wiki/view/Addon.xml#Dependency_versions, может всё-таки у вас другая версия Kodi. Загрузите `kodi.log` с ошибкой на pastebin.org, чтобы лучше разобраться с проблемой.

**Comment by Dimasua** [comment]
Загрузил последний вариант сборки с Kodi - xbian. С ним выдаёт другую
ошибку: "the dependency on script.module.m3u8 version 0.5.4 could not be
satisfied."

**Comment by quarckster** [comment]
Похоже, что в Xbian отключены стандартные репозитории Kodi. Вот здесь похожая проблема https://github.com/quarckster/kodi.kino.pub/issues/184.
