### ISSUE TITLE
Все стало открываться очень долго

### ISSUE THREAD

**Issue by VyacheslavTeplyakov** [quarckster/kodi.kino.pub#189]
Примерно с неделю или две назад, как я думаю на стороне сервиса произошли некие изменения. Теперь на любой версии плагина, что на супер старых, что на самой последней, крайне долго открываются потоки. Отваливаются по таймауту. Проблема точно на стороне KODI, потому что с веб морды все летает хоть в 4к. Тут же приходится перебирать все подряд потоки и ждать по минуте, в надежде что хоть один из них запустится. Ситуация напоминает открытие потока в который вшито 100500 звуковых дорожек и субтитров. Если оно запускается, то проигрывает без проблем дальше. Т.е. лажа где-то на разборе заголовка или что-то такое. В логе пишет просто таймаут и всё. Если ссылку из лога на этот поток открыть в браузере, открывается мгновенно. 
Протестировано на версиях с 17 по 19. Установки чистые, версии стейбл, других репо или расширений нет. Не знаю что делать.

**Comment by quarckster** [comment]
Пишите в поддержку кинопаба.

**Comment by quarckster** [comment]
Пишите в поддержку кинопаба.
