### ISSUE TITLE
Support profiles

### ISSUE THREAD

**Issue by bossanova808** [quarckster/kodi.kino.pub#197]
https://github.com/quarckster/kodi.kino.pub/blob/a657fe247b66aa560b574ce2855cc6db6379f1a2/src/resources/lib/settings.py#L8

...should perhaps change that to:
`xbmcvfs.translatePath("special://profile/advancedsettings.xml")`

...to pick up the advancedsettings.xml of the current profile, rather than always the master user...

**Comment by quarckster** [comment]
Thanks for the tip!
