### ISSUE TITLE
Ошибка плагина при поиске.

### ISSUE THREAD

**Issue by olsamurai** [quarckster/kodi.kino.pub#20]
Мне пока удалось найти только один случай, но зато он првторяем.

Заходим в раздел поиск и вводим "planes" и жмём поиск. Появляется ошибка плагина.

Если нужен кусочек лога, то могу прикрепить завтра вечером после работы.

**Comment by quarckster** [comment]
Оказывается иногда API кинопаба может возвращать длительность видео как 0.
