### ISSUE TITLE
Проблема с установкой на Libreelec

### ISSUE THREAD

**Issue by Veidali** [quarckster/kodi.kino.pub#201]
**Describe the bug**
При установке на LibreELEC (версия скачана через тул для создания загрузочной флешки) ругается на отсутствие xbmc.python 3.0.0

**To Reproduce**
Действовал по инструкции.
Чистый коди после установки, выбран только язык интерфейса, раскладка и местоположение.
По инструкции - скачал zip с репозиторием и через репозиторий попытался установить адд-он кинопаба.
При установке выдает сообщение что не нашел xbmc.python 3.0.0

**Comment by quarckster** [comment]
`xbmc.python 3.0.0` доступен в Kodi 19 и выше.

**Comment by Veidali** [comment]
Спасибо. Действительно, на стабильной LibreElec еще 18.9
