### ISSUE TITLE
Can’t display the language of subtitles 

### ISSUE THREAD

**Issue by kesha** [quarckster/kodi.kino.pub#204]
Использую версию 3.0.4

При выборе субтитров показывает ID вместо языка. Найти нужные можно только перебором.

**Comment by quarckster** [comment]
Насколько я понимаю, это не проблема плагина. Он всего лишь передаёт в Kodi то, что приходит через API кинопаба. Например, на этом видео есть и просто id, так субтирты с языком:
![image](https://user-images.githubusercontent.com/1011257/129611388-beebdf3a-bfd4-49c6-a55a-7e7eb6e05726.png)
