### ISSUE TITLE
Нет возможности выбрать аудиодорожку при просмотре через kodi

### ISSUE THREAD

**Issue by webestet** [quarckster/kodi.kino.pub#206]
При нажатии в плагине на `Переключить аудиодорожку` не происходит ровным счетом ничего. Зашита русская дорожка. Как добраться до остальных?
Полагаю это баг плагина.

**Comment by webestet** [comment]
Есть множество подобных `issues` закрытых с ответами. Это дубликат

**Comment by kesha** [comment]
Используй http стримминг
