### ISSUE TITLE
urllib сертификат закончился

### ISSUE THREAD

**Issue by iga2iga** [quarckster/kodi.kino.pub#207]
После установки всех последних обновлений на Win10, включая необязательные на сегодняшний день происходит следующее:
для 3.0.5
при попытке активации нового устройства получаю ошибку в коди "ошибка плагина, смотрите журнал",
в журнале - urllib эксепшн. действие сертификата закончилось.
для 3.0.3 генерируется код при активации, время тикает. но при добавлении кода на сайте сразу же "ошибка плагина, смотрите журнал". Скорее всего та же самая ошибка сертификата.
проверял в kodi 19.0, 19.1 и ночнушке 20.0

**Comment by quarckster** [comment]
Плагин целиком и полностью полагается на сертификаты системы. Никакого "своего" TLS стека не реализовано. Скорее всего вам надо обновить сертификаты на вашей системе.

**Comment by Eviloid** [comment]
Мне удалось решить эту проблему для Kodi19 под Windows добавлением сертификата  [R3, Let's Encrypt](https://letsencrypt.org/certs/lets-encrypt-r3.pem) в конец файла C:\Program Files\Kodi\system\certs\cacert.pem

**Comment by iga2iga** [comment]
> Мне удалось решить эту проблему для Kodi19 под Windows добавлением сертификата [R3, Let's Encrypt](https://letsencrypt.org/certs/lets-encrypt-r3.pem) в конец файла C:\Program Files\Kodi\system\certs\cacert.pem

Работает, спасибо. Я просто заменял https на http в auth.py и client.py, так тоже работает.

**Comment by quarckster** [comment]
>Я просто заменял https на http в auth.py и client.py плагина
Лучше всё-таки починить сертификат, чем нешифрованный трафик гонять.

**Comment by iga2iga** [comment]
> > Я просто заменял https на http в auth.py и client.py плагина
> 
> Лучше всё-таки починить сертификат, чем нешифрованный трафик гонять.

Да, вставил сертификат в Kodi, вернул https. Но видимо проблема с последними необязательными обновлениями Windows 10. Т.к. на необновленной необязательными обновлениями 21H1 всё работает на 19.1 + 3.0.5. И скорее всего проблема в обновлениях типа "Предварительная версия исправлений..." Ну либо не проблема, а фича :)
