### ISSUE TITLE
Selected item after stopping playback

### ISSUE THREAD

**Issue by olsamurai** [quarckster/kodi.kino.pub#21]
Выбранный элемент в списке теряется после обновления экрана и фокус прыгает на самый верх. Если можно было бы подправить, было бы классно.
Выглядит так, ставим на воспроизведение, потом останавливаем или же заканчивается воспроизведение и выбранный элемент становится корень списка.

**Comment by quarckster** [comment]
Это поведение Kodi. После остановки воспроизведения делается `Container.Refresh`, чтобы обновить список, и после этого фокус смещается на корень. API Kodi не позволяет нормально решить эту проблему. Максимум что у меня получалось, это вернуть фокус через 3 секунды после обновленя списка, и выглядит это по-дурацки. Фокус скачет по списку.

**Comment by olsamurai** [comment]
Спасибо за объяснение! Тогда можно закрывать тикет.
