### ISSUE TITLE
Плагин не устанавливается на последнюю версию Libreelec

### ISSUE THREAD

**Issue by 2scorpio** [quarckster/kodi.kino.pub#214]
Пишет требуемое дополнение xbmc.python версии 3.0.0 не найдено
Где взять это дополнение ?

**Comment by quarckster** [comment]
Плагин версий 3.x требует Kodi 19 и выше. Для старших версий используйте https://github.com/quarckster/kodi.kino.pub/releases/tag/2.12.4.

**Comment by 2scorpio** [comment]
Тогда пишет требуемое дополнение xbmc.python версии 2.25.0 не найдено

**Comment by quarckster** [comment]
Какой версии Kodi установлен в Libreelec? Установлен ли python в системе вообще? Проблема однозначно в сборке Libreelec.

**Comment by 2scorpio** [comment]
установлен Team Kodi - 1.5.1+matrix.1
это я вижу в поиске по python
как я могу увидеть версию kodi ?

**Comment by 2scorpio** [comment]
Kodi версии 19.0

**Comment by 2scorpio** [comment]
нашёл xbmc.python-2.25.0.zip
пытаюсь поставить из zip - просто мелькает экран и модуль не добавляется

**Comment by 2scorpio** [comment]
точная версия kodi 19.3
в качестве python стоит InputStream 0.5.8+matrix.1

**Comment by quarckster** [comment]
Проблема с Libreelec, не с плагином. Если плагин не устанавливатеся с ошибкой `xbmc.python`, то никакие другие Kodi дополнения не установятся.

**Comment by 2scorpio** [comment]
питон в системе присутствует.
сторонние плагины ставятся.
![send01](https://user-images.githubusercontent.com/36969533/146828971-dcab314e-6d41-4aa1-84eb-b44d955b4004.jpg)

**Comment by quarckster** [comment]
Установил Libreelec 10.0.1 в виртуальную машину. Плагин успешно установился
![image](https://user-images.githubusercontent.com/1011257/146832220-c7f6e115-40ab-4db1-b78c-1590b4c7724c.png)

**Comment by 2scorpio** [comment]
Перезалил образ. Заработало.
Спасибо !
Скажите, а HLS4 на Pi4 работает ?

**Comment by quarckster** [comment]
Устновите inputstream.adaptive и должно заработать.
