### ISSUE TITLE
Не удаётся активировать устройство

### ISSUE THREAD

**Issue by vladpozh** [quarckster/kodi.kino.pub#216]
Здравствуйте!

Подскажите, пожалуйста, как активировать устройство в приложении kodi?
При активации выскакивает ошибка:
“kino.pub error”
![Uploading 4270BAE2-0099-4335-B9F5-844F5708AA26.jpeg…]()

Приложение kodi-19.3-Matrix установлено на Windows
Используется плагин - video.kino.pub-3.1.0

**Comment by quarckster** [comment]
Здравствуйте, приложите пожалуйста `kodi.log` https://kodi.wiki/view/Log_file

**Comment by vladpozh** [comment]
Пожалуйста:
[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/7803610/kodi.log)
Спасибо за оперативность)

**Comment by quarckster** [comment]
@vladpozh похоже, что у вас эта проблема https://github.com/quarckster/kodi.kino.pub/discussions/211#discussion-3618324

**Comment by vladpozh** [comment]
Огромное Вам спасибо!
Помогло)
Хорошего вечера)
