### ISSUE TITLE
Не появляется код для активации на kinopub

### ISSUE THREAD

**Issue by vladst15** [quarckster/kodi.kino.pub#217]
Делаю все по инструкции, после добавления плагина, появляется иконка о том, что плагин установлен, затем запускаю плагин и выдает ошибку. Сертификат lets-encrypt-r3 добавлял, проблема не исчезла.

**Comment by imkaef** [comment]
some problem

**Comment by nikolaev-rd** [comment]
Это на какой версии? А то я с v2.12.4 до 3.1.2 (последней на данный момент) обновляться собрался.

**Comment by stavultras** [comment]
это у вас проблема с сетью, 99%. покажите логи kodi.log. У меня активация работает на всех версиях. Так же проверьте доступ к https://api.support-kp.com/v1/. Должно вернуть OK.
