### ISSUE TITLE
Фильтр элементов в основном списке

### ISSUE THREAD

**Issue by olsamurai** [quarckster/kodi.kino.pub#22]
Вначале хочу сказать, что плагин стал очень удобным и комфортным! Большое спасибо!

Такая вот хотелка:
В основном списке некоторые элементы используются очень редко или совсем не используются. Можно как-то реализовать изменение основного списка. К примеру, убрать вкладки 3D, 4K, ТВ, а "подборки" в самый конец списка. Можно как-нибудь файлом конфигурации в формате json или xml.

P.S. Отображение ответа HTTP сервера просто бомба! Вчера сэкономил время и нервы. Всё просто и лаконично: ответ сервера 500.

**Comment by quarckster** [comment]
я думаю, можно попробовать через настройки это сделать.
