### ISSUE TITLE
Не определяется язык субтитров

### ISSUE THREAD

**Issue by kolnogorov** [quarckster/kodi.kino.pub#224]
**Describe the bug**
В видео не определяется язык субтитров - для каждых субтитров он указан как Unknown. Таким образом, не работает автовыбор нужного языка, и если в видео несколько субтитров на разных языках, приходится перебором искать нужный.

**To Reproduce**
1. Включить любое видео
2. Открыть настройки субтитров и посмотреть на список
3. У всех субтитров язык будет указан как Unknown

**Actual results**
Выбирается всегда первая дорожка субтитров, вне зависимости от того, какой язык по умолчанию выбран в настройках, а так же невозможно выбрать нужный язык, когда их много

**Expected behavior**
В списке субтитров должен быть указан язык, а так же должен работать автовыбор субтитров на нужном языке.

**Comment by quarckster** [comment]
Плагин не может с этим помочь, это сугубо проблема Kodi. Плагин только передаёт метаданные и ссылку на поток. Kodi не может распознать язык субтитров из потока.
