### ISSUE TITLE
IMDB и Кинопоиск рейтинги

### ISSUE THREAD

**Issue by stavultras** [quarckster/kodi.kino.pub#23]
Спасибо за обновление, особенно порадовало управление закладками. У меня есть пару предложений по улучшению рейтингов.
Что я сделал у себя в локальной версии:
1. Перенёс рейтинги над описанием (когда они были после описания и описание длинное, их просто не было видно): 
![3xwno2e](https://user-images.githubusercontent.com/6468524/48475547-1ee04300-e80e-11e8-8d7b-f312d510358c.jpg)
2. Для сериалов добавил статус сериала: окончен, в эфире) 
![3xwnr0i](https://user-images.githubusercontent.com/6468524/48475621-40412f00-e80e-11e8-872d-9e30ea9fb9b0.jpg)
![3xwnt45](https://user-images.githubusercontent.com/6468524/48475650-4d5e1e00-e80e-11e8-9358-08d7a324612f.jpg)

P.S.: так же добавил год, рядом с рейтингами.

Мне кажется что так более удобней пользоваться рейтингами. Если нужно могу свои правки выложить.
Спасибо.

**Comment by olsamurai** [comment]
Полностью поддерживаю!
Было бы не плохо еще жанр отображать и, если это возможно, автоскроллинг для описания встроить.

**Comment by quarckster** [comment]
@stavultras да, давайте в виде PR оформим.

**Comment by stavultras** [comment]
@quarckster не совсем уверен, что я правильно сделал PR :-)

**Comment by quarckster** [comment]
#25 merged

**Comment by stavultras** [comment]
@olsamurai на счет прокрутки сюжета, если у Вас тема Estuary, то это можно включить вот тут (в настройках темы):
![2018_11_17_20_59_32_663](https://user-images.githubusercontent.com/6468524/48664173-cfb73e00-eaab-11e8-9394-6ce1bc7a4dbd.jpg)

**Comment by olsamurai** [comment]
Спасибо, завтра попробую.
