### ISSUE TITLE
Работа плагина в Kodi на Xbox Series S и X

### ISSUE THREAD

**Issue by shu-all** [quarckster/kodi.kino.pub#240]
1. Плагин кинопаба в kodi на консолях Series S/X сильно тормозит.  Конкретно тормозит навигация по меню. После подтверждения любого действия идёт загрузка порядка нескольких минут. К примеру, в главном меню нажал фильмы - жди 2 минуты загрузки экрана с фильмами. И так с любыми действиями. 
2.  На Series S  плагин не может загрузить фильм со всеми дорожками в качестве 1080p. Series X справлялся и в 4к (правда в РФ, возможно имеет значение).
3.  Плагин на Series S не справляется с длинными фильмами с одной дорожкой в качестве 1080р (если выставить в настройках hls4). Идёт загрузка и потом обрывается. В РФ, с Series X и 4к потоком такой проблемы не было.
4.  Скорость находясь в Тайланде с консоли  Series S и kodi выглядит хуже чем через браузер консоли или другое устройство (браузер ipad, android app).
По убывающей,  по скорости (тест скорости, мбит):
- android app (нид 39,5  рос 8,7)
- браузер ipad (нид 7,7 рос 2,8)
- браузер xbox edge (нид 0,3  рос 12,2)
- плагин kodi на xbox неизвестно (нет встроенного теста скорости), но субьективно подгрузки во время просмотра случаются чаще и длительнее чем у других вариантов выше.

**Comment by quarckster** [comment]
Очень похоже на это https://github.com/quarckster/kodi.kino.pub/discussions/233
