### ISSUE TITLE
Пропала опция "Я Смотрю" из контекстного меню

### ISSUE THREAD

**Issue by po1vo** [quarckster/kodi.kino.pub#251]
Пропала около месяца назад.

![Screenshot_20230202_150856](https://user-images.githubusercontent.com/3443972/216438982-790f34a1-f7bd-4e9f-9359-a466b61df10a.png)

**Comment by Kampfader** [comment]
@po1vo Можешь поделиться, что это за скин такой у тебя?
спасибо

**Comment by po1vo** [comment]
@Kampfader Arctic Zephyr Reloaded
