### ISSUE TITLE
Не обновляются статусы видео, перескакивает курсор.

### ISSUE THREAD

**Issue by vevsvevs** [quarckster/kodi.kino.pub#26]
Огромное спасибо за развите плагина! Поддержка паба ранее говорила, что разработка остановлена, так что эта версия стала очень приятным сюрпризом :)

К сожалению, у меня возникли некоторые проблемы:
- просле просмотра чего-либо, курсор всегда перескакивает в начало списка;
- "отметить как.." не обновляют иконку статуса до повторного входа в папку;
- "воспроизвести отсюда" - аналогично предыдущему.

Кнопки "отметить как.." использовал именно плагина (не Kodi). Мне кажется, что всё это связано с механизмом обновления текеущего представления списка, поэтому не стал создавать отдельные проблемы. Окружение: версия плагина 2.2.1 на CoreElec 8.95.4.3 (Kodi18.0-BETA5 Git:5b29afbf1aab164ebce6a600a88c4215e90ef92d).

**Comment by vevsvevs** [comment]
Ага, в закрытых тикетах нашёл. Правильно ли я понимаю, что связано это с Container.Refresh? Т.е. первая проблема - из-за его вызова после просмотра для обновления статуса, вторая и третья - из-за его НЕ вызова после отработки команды? Получается, что единственная причина вызова Container.Refresh - немедленное обновление статусов, но при этом происходит сброс выбранного элемента, что крайне неудобно для просмотра сериалов :) Возможно, раз в других частях интерфейса поведение иное - стоит пожертвовать моментальным обновлением статуса и при обычном просмотре? Мне кажется, перескок селектора вызывает больше проблем.

**Comment by stavultras** [comment]
@vevsvevs я у себя обновление контейнера временно отключил в двух местах. Ибо долговато крутился кружек загрузки Kodi.

**Comment by vevsvevs** [comment]
Ну так он каждый раз тянет метаданные по всем элементам списка с паба, получается? Не скажу, что прям сильно напрягает, но тоже уберу, пожалуй, из-за перескоков.. Но очень надеюсь, что более красивое решение всё-таки найдётся :)

**Comment by quarckster** [comment]
@vevsvevs давайте для каждой проблемы сделаем отдельный тикет. Не совсем понятно что со статусами, видео не отмечается как просмотренное?

**Comment by quarckster** [comment]
@vevsvevs в [2.3.0](https://github.com/quarckster/kodi.kino.pub/releases/tag/2.3.0-beta.1) я убрал вызовы `Container.Refresh` после остановки воспроизведения.

**Comment by vevsvevs** [comment]
@quarckster совершенно верно, речь об отметках просмотрено/частично просмотрено.  Думаете, стоит вопрос разделить? Насколько я понял, причина-то одна и та же - невозможность обновить представление статусов без обновления всего контейнера с последующей потерей фокуса выбранного элемента. Соответственно, решения п.1 и пп.2-3 взаимоисключающие: либо везде вызывать `Container.Refresh` и терять фокус, либо везде убрать его вызов и лишиться моментального обновления представления. Второй вариант лично мне кажется меньшим из двух зол, ведь что мы только что посмотрели - мы и так знаем, а вот листать всякий раз от начала списка неудобно. Здорово, что вы пришли к тому же мнению :) В принципе, тикет можно закрывать, если другой возможности решить проблему не существует (например, кэширование списка и обновление представления локально поэлементно, а полная синхронизация с источником - только при входе в папку, если API Kodi это позволяет).
