### ISSUE TITLE
Plugin fail to play any video (kodi ver.19 plug-in ver. 3.4.1)

### ISSUE THREAD

**Issue by Zayaczlo** [quarckster/kodi.kino.pub#265]
Not working on kodi 19 and add-on 3.4.1. 

To Reproduce

Find any movie/episode
Start it.

Actual results
Error popup

![IMG_20230223_171548](https://user-images.githubusercontent.com/126174749/220934652-f8b5791c-a3ad-4d32-bc93-9f23e7a29528.jpg)

**Comment by nsine** [comment]
+1 Same problem when selecting HLS4 stream (works with others though). 
The log says "Error creating demuxer".

**Comment by nsine** [comment]
@Zayaczlo can you try disabling SSL (from website) and see if it'll work? 
Not sure if you have same issue as I faced, but looks like ffmpeg is not able to open stream under `https`

**Comment by quarckster** [comment]
Not a plugin issue.
