### ISSUE TITLE
4x the same Audiostreams

### ISSUE THREAD

**Issue by Kampfader** [quarckster/kodi.kino.pub#271]
**Describe the bug**
The audio tracks are shown more than on the web page.

Kodi 20.1 on Android System (firetv cube)
Addon Version 3.4.1
InputStream Adaptive - Active

See pic
![firetv_2023-03-27_15_06_08](https://user-images.githubusercontent.com/23200748/227947719-5503d0a5-7790-4b61-b614-15b237677e98.jpg)

If you need a debug.log then email me where I can send it.

**Comment by Kampfader** [comment]
Im testing with this #278 on kodi omega Alpha.

On http, hls, hls2 streams i have only one Audiostream.

On hls4 streams, i have now not 4 the same Audiostreams, but 6.

**Comment by relictMarauder** [comment]
IMHO this is not a problem of the AddOn.  The this problem, is already fixed in [inputstream.adaptive v. 21.2.0-Omega](https://github.com/xbmc/inputstream.adaptive/releases/tag/21.2.0-Omega)
