### ISSUE TITLE
Как добавить zip файл

### ISSUE THREAD

**Issue by a0s** [quarckster/kodi.kino.pub#277]
Kodi 20.1 на SteamDeck не показывает ни одного zip файла ни в какой папке. Сторонние источники разрешены. В чем может быть проблема?

**Comment by quarckster** [comment]
Извините, но вы обратились не по адресу. Вам в поддержку SteamDeck и Kodi.

сб, 22 апр. 2023 г., 12:41 Anton Osenenko ***@***.***>:

**Comment by a0s** [comment]
Понимаю, просто подумал может быть формат метаданных в zip архиве поменялся, и kodi перестал узнавать ваши сборки, поэтому и не показывает их в списке файлов. Но.. маловероятно. Спасибо
