### ISSUE TITLE
The config parameter use_inputstream_adaptive name is not in sync with implementation

### ISSUE THREAD

**Issue by relictMarauder** [quarckster/kodi.kino.pub#278]
In settings.xml 
to save the flag for using of inputstream adaptive is named "use_inputstream_adaptive" 
https://github.com/quarckster/kodi.kino.pub/blob/9ff1678232374002803ed70024dfda4e4d2ae462/src/resources/settings.xml#L74
and in implementation "inputstream_adaptive_enabled" used.
https://github.com/quarckster/kodi.kino.pub/blob/9ff1678232374002803ed70024dfda4e4d2ae462/src/resources/lib/plugin.py#L254 is

**Comment by quarckster** [comment]
Good catch, thank you!
