### ISSUE TITLE
api url не работает ни с одного провайдера ни с одним впн

### ISSUE THREAD

**Issue by yskultan** [quarckster/kodi.kino.pub#312]
ни один из этих адресов недоступен. https://api.service-kp.com/v1, https://api.srvkp.com/v1. впн, смена провайдера и устройства не помогают. https://api.support-kp.com/v1/ выдает ОК при любом исходе. из-за недоступности урлов не могу активировать устройство - 110 ошибка в логах

**Comment by quarckster** [comment]
не подтверждаю.
