### ISSUE TITLE
Не работает активация устройства на LibreELEC

### ISSUE THREAD

**Issue by Bendy3192** [quarckster/kodi.kino.pub#320]
**Описание бага**
При нажатии на кнопку "Активировать устройство" вижу сообщение "Ошибка kino.pub См. журнал чтобы узнать подробнее. Пробовал также использовать VPN и менять локацию в самом кинопабе. LibreELEC 11.0.4, Kodi v20.2

**Чтобы повторить**
Шаги чтобы повторить ошибку:
1. Зайти в аддоны
2. Нажать на Kino.Pub
3. Нажать "Активировать устройство"
4. Получить ошибку

**Скриншоты**
![IMG_20240108_020429](https://github.com/quarckster/kodi.kino.pub/assets/104999566/c397b383-cf1a-4edf-ad06-1dadd9ecc387)

**Дополнительная информация**
Прошу прощение за отсутствие логов, не нашел как получить логи кинопаба..

**Comment by quarckster** [comment]
Логи кинопаба пишутся вместе с логами Kodi, https://kodi.wiki/view/Log_file

**Comment by Bendy3192** [comment]
@quarckster Проблема оказалась в блокировке Кинопаба моим провайдеров. С VPN все работает, но тут уже другая проблема — сам VPN бесплатный и работает не очень. Я знаю, что у Кинопаба есть что-то вроде своих зеркал, чтобы можно было использовать сайт без VPN. Скажите, можно ли как-то смотреть кинопаб на LibreELEC/Linux Mint + Kodi без VPN? Может прокси какой нибудь есть.. Спасибо!

**Comment by quarckster** [comment]
> @quarckster Проблема оказалась в блокировке Кинопаба моим провайдеров. С VPN все работает, но тут уже другая проблема — сам VPN бесплатный и работает не очень. Я знаю, что у Кинопаба есть что-то вроде своих зеркал, чтобы можно было использовать сайт без VPN. Скажите, можно ли как-то смотреть кинопаб на LibreELEC/Linux Mint + Kodi без VPN? Может прокси какой нибудь есть.. Спасибо!

Это не проблема плагина
