### ISSUE TITLE
Authorization on xbox x

### ISSUE THREAD

**Issue by RodionakaRady** [quarckster/kodi.kino.pub#338]
Привет. Я поиском попользовался, но ответ не нашел. Пытаюсь через kodi поставить на x-box. Делал по инструкции, но при нажатии на «activate device” после установки аддона получаю ошибку кино.паб error. 

Делал по инструкции с кинопаба коди

**Comment by quarckster** [comment]
Приет, нужен лог Kodi. https://kodi.wiki/view/Log_file

**Comment by RodionakaRady** [comment]
Файл пуст. Хотя вроде после ошибки он пишет текст про сохранения ошибки в Лог. 

Такая ошибка может быть из-за подключения из России без vpn?

**Comment by stavultras** [comment]
> Такая ошибка может быть из-за подключения из России без vpn?

https://api.srvkp.com/v1 открывается в браузере? Должно быть "404 Not Found"

**Comment by RodionakaRady** [comment]
Нет, не открывается (не удается открыть страницу)
А вот с vpn’ом дает 404ую.

**Comment by stavultras** [comment]
> Нет, не открывается (не удается открыть страницу)
ну вот собственно и ответ. плагин ни при чем выходит.

**Comment by RodionakaRady** [comment]
Тогда последний вопрос: авторизация только разовая или постоянная? Или запрос на эти «подvpn’ые» адреса постоянно идут или только при авторизации?

**Comment by stavultras** [comment]
> Тогда последний вопрос: авторизация только разовая или постоянная? Или запрос на эти «подvpn’ые» адреса постоянно идут или только при авторизации?

Постоянно конечно. Это же общий API - авторизация, список серий, фильмов, закладки и т.д.
