### ISSUE TITLE
перемотка видео на http vs hls

### ISSUE THREAD

**Issue by superyarik** [quarckster/kodi.kino.pub#344]
почему-то при http стриме не могу перемотать видео, выкидывает на постер фильма, хотя при заходе с начала все играет.
при стриминге hls перемотки работает(но очевидно не работает выбор аудиодорожки). это как-то можно побороть?

**Comment by stavultras** [comment]
Насколько я помню, HTTP не поддерживается самим облаком, где размещены видео. Оно ещё работает, но с такими глюками, как вы описали. Плагин тут ни при чём. В новых версиях плагина вообще нет выбора HTTP.
