### ISSUE TITLE
Здравствуйте! Приложение для kodi 18 не запускается.  На этапе добавления устройства выдает ошибку. 

### ISSUE THREAD

**Issue by Smirnoff2017** [quarckster/kodi.kino.pub#351]
**Describe the bug**

**To Reproduce**

**Actual results**
What does happen after the last step?

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Smirnoff2017** [comment]
![IMG_6642](https://github.com/quarckster/kodi.kino.pub/assets/174301418/1481c942-3b43-4fb0-84cc-54f3d9d1631e)

**Comment by Smirnoff2017** [comment]
![IMG_6643](https://github.com/quarckster/kodi.kino.pub/assets/174301418/cdc78804-8437-4d0c-b877-e6d915b7cd0f)

**Comment by stavultras** [comment]
А вы какую версию ставите? Для Kodi 18 последняя рабочая 2.12.4.

**Comment by Smirnoff2017** [comment]
Здравствуйте! Именно её и ставлю. Уже несколько раз переставлял. Отправлено с iPhone1 июля 2024 г., в 12:19, Dmitry Mostovoy ***@***.***> написал(а):﻿
А вы какую версию ставите? Для Kodi 18 последняя рабочая 2.12.4.

**Comment by stavultras** [comment]
@Smirnoff2017 ну нужно логи смотреть, что там не так и почему ошибка. без логов невозможно сказать. у меня на kodi 18 работает нормально.

**Comment by Smirnoff2017** [comment]
В браузере айпада, айфона все прекрасно работает. Но там через зеркало.А тут даже новое устройство добавляется некорректно. В журнале ошибок ничего нет(Есть смысл переустановить все или настройки какие-то покрутить?Отправлено с iPhone1 июля 2024 г., в 15:25, Dmitry Mostovoy ***@***.***> написал(а):﻿
@Smirnoff2017 ну нужно логи смотреть, что там не так и почему ошибка. без логов невозможно сказать. у меня на kodi 18 работает нормально.

**Comment by stavultras** [comment]
Можно конечно попробовать поправить саму библотеку - файл resources/lib/client.py. Заменить https://api.service-kp.com/v1 на https://api.srvkp.com/v1.

**Comment by Smirnoff2017** [comment]
Ой ой! А где это сделать?)Отправлено с iPhone1 июля 2024 г., в 15:53, Dmitry Mostovoy ***@***.***> написал(а):﻿
Можно конечно попробовать поправить саму библотеку - файл resources/lib/client.py. Заменить https://api.service-kp.com/v1 на https://api.srvkp.com/v1.

**Comment by Smirnoff2017** [comment]
Снова здравствуйте! Простите за назойливость, но это уже дело принципа теперь! Поставил OSMC версия 20.5.0Установил kinopub 3.6.0. Установил обновления всего и вся! Всех плагинов, всех браузеров! И такая же фигня!  Нажимаю активмроввть устройство - выдает ошибку! Ну подскажите что делать!!!!!!!!😢😢😢😢😢Отправлено с iPhone1 июля 2024 г., в 15:53, Dmitry Mostovoy ***@***.***> написал(а):﻿
Можно конечно попробовать поправить саму библотеку - файл resources/lib/client.py. Заменить https://api.service-kp.com/v1 на https://api.srvkp.com/v1.

**Comment by stavultras** [comment]
Это особо ничего не даст, и тот и другой работает, если не заблочено провадером. Без kodi.log с ошибкой помочь нереально. Тут нетипичная какая-то ошибка.

**Comment by Smirnoff2017** [comment]
[uploadlog.txt](https://github.com/user-attachments/files/16238898/uploadlog.txt)
Здравствуйте! я поставил 19 Коди, поставил последнею версию кинопаба, пообновлял все возможные дополнения но опять ошибка. скачал все логи можете глянуть

> Это особо ничего не даст, и тот и другой работает, если не заблочено провадером. Тем более устройство пытается активироваться - значит не заблочено. Без наличия kodi.log с ошибкой - помочь нереально. Тут нетипичная какая-то ошибка.

**Comment by Smirnoff2017** [comment]
> Это особо ничего не даст, и тот и другой работает, если не заблочено провадером. Тем более устройство пытается активироваться - значит не заблочено. Без наличия kodi.log с ошибкой - помочь нереально. Тут нетипичная какая-то ошибка.

[video.kino.pub]: http proxy settings are not correct
вот такая ошибка! Нашел в логах этих!

**Comment by quarckster** [comment]
У вас в настройках [Kodi](https://kodi.wiki/view/Settings/System/Internet_access) используется прокси-сервер и его настройки неправильные. Убедитесь, что адрес сервера длинне 3 символов и номер порта больше 0. Или отключите прокси сервере вообще.

**Comment by Smirnoff2017** [comment]
[uploadlog.txt](https://github.com/user-attachments/files/16240046/uploadlog.txt)
посмотрите пожалуйста логи!!(

**Comment by quarckster** [comment]
Ошибка в том, что плагин не может соединиться с кинопабом. У вас проблема с сетью, ошибка не в плагине.

**Comment by Smirnoff2017** [comment]
![2024-07-16_00-06-26](https://github.com/user-attachments/assets/832b73f5-02e3-471e-831a-6ff7df698f92)
вот такое еще нашел

**Comment by Smirnoff2017** [comment]
[uploadlog.txt](https://github.com/user-attachments/files/16240366/uploadlog.txt)

**Comment by Smirnoff2017** [comment]
Куда копать подскажите!
На айфоне все работает! Приложение нет(
