### ISSUE TITLE
Минимум один файл не может быть проигран.

### ISSUE THREAD

**Issue by olsamurai** [quarckster/kodi.kino.pub#36]
Раньше не доходили руки протестировать. Ситуация следующая: берём сериал викинги, 5 сезон 15 серия. Запускаем на просмотр. Долго крутится в ожидании, а потом выдает: минимум один файл не может быть проигран. И так повторяется хоть 30 раз. То же самое на ноутбуке или на Андроиде проигрывает 10 раз из 10. Подключение по кабелю через один роутер. Все происходит только на Коди.

**Comment by quarckster** [comment]
Не могу подтвердить у себя, всё воспроизводится. Какой поток выбран в настройках? Если hls4, то он не поддерживается kodi. Плагин не воспроизводит поток, он только извлекает ссылку на него и передаёт его коди

**Comment by stavultras** [comment]
Такая фигня бывает когда один из серверов облака начинает гнать. То потоки вылетают, то Коди подвисает, мне лично помогает переключение сервера с России на Германию в ЛК.
