### ISSUE TITLE
Trakt.tv скробблинг

### ISSUE THREAD

**Issue by goooseman** [quarckster/kodi.kino.pub#37]
Есть сервис для скробблинга просмотренных фильмов и сериалов [Trakt.tv](https://trakt.tv).

У них есть [плагин для Kodi](https://github.com/trakt/script.trakt), который отправляет все просмотренное в Trakt.tv и позволяет поставить оценку просмотренному.

Выглядит это вот так:

![Rating](http://i.imgur.com/7IayOWr.png)

Если смотрим фильмы и сериалы через плагин Kino.pub, Trakt.tv не узнает об этом по понятным причинам.

Я хочу реализовать сам такой функционал в плагине, но я в жизни не касался разработки плагина для Kodi, поэтому сначала хотел уточнить как лучше и как вообще возможно это сделать.

Я вижу три варианта:

1. Сделать что-то, что позволит нам работать с родным плагином trakt.tv. Или сделать так, чтобы плагин сам видел, что мы смотрели. Или может быть вызывать какой-то публичный метод плагина trakt?
Из документации: `Add-ons that stream content need to correctly identify TV episodes and movies with as much metadata as possible for Trakt to know what you're watching.` `...` `TV shows are identified by TVDb ID or IMDb ID. Movies are identified by TMDb ID or IMDb ID. This allows Trakt to match the correct show or movie more accurately, regardless of the title. The best supported and recommended configuration is to use TVDb (for tv shows) and TMDb (for movies) as your scrapers.`  То есть может быть нам всего лишь не хватает метаданных TMDb/IMDb/TVDb?

2. Сделать свой скробблинг в trakt внутри плагина. То есть в настройках кинопроб плагина будет аутенфикация в trakt, и плагин сам будет делать запрос в их API. Звучит как сложно и не нужно.

3. На худой конец есть ли у кинопаба API, который выдает информацию о просмотренном пользователем? Если так, то на худой конец я готов написать просто внешний daemon, который будет крутится у меня на сервере, забирать информацию с кинопаба и отправлять в trakt.

Что думаете? Насколько это возможно и с чего начать?

**Comment by goooseman** [comment]
Нашел [документация для авторов стриминговых плагинов](https://github.com/trakt/script.trakt/wiki/Providing-id's-to-facilitate-scrobbling)

Перед воспроизведением медиа нам надо добавить следующий код:
```
ids = json.dumps({u'tmdb': 264660, u'imdb': u'tt0470752', u'slug': u'ex-machina-2014', u'trakt': 163375})
xbmcgui.Window(10000).setProperty('script.trakt.ids', ids)
```

Список ID'шников может быть сильно меньше

**Comment by goooseman** [comment]
Начал работу над этим таском у себя в форке: https://github.com/goooseman/kodi.kino.pub/tree/feature/trakt-tv

**Comment by quarckster** [comment]
Только сделайте эту фичу отключаемой в настройках.

**Comment by goooseman** [comment]
@quarckster это всего лишь установление свойства на объект окна.
То есть если плагина trakt.tv нет, то ничего не изменится.
я изучил другие плагины стриминга фильмов, у которых оно есть - там эта функция не отключается, так как ее присутствие ничего не меняет

**Comment by quarckster** [comment]
оке, ждём пулл реквеста.

**Comment by goooseman** [comment]
Из какой ветки делать свою ветку?
Я сначала сделал из dev по концепции git flow, но в ней версия не в очень рабочем состоянии.
Во-первых, там используется `import web_pdb; web_pdb.set_trace()`, но в `addons.xml` отсутствует `<import addon="script.module.web-pdb" />`.
Во-вторых, там и дальше есть ошибка по поводу `setResumeTime`.

Я начал в итоге ветку из `master`, ok?

**Comment by quarckster** [comment]
На гитхабе все пулл реквесты обычно делаются в мастер, если обратное не оговорено в репе. Так что да, смело делайте свою ветку из мастера, потом пушьте её в своюб репу, а потом уже пулл реквест сюда.
