### ISSUE TITLE
Speedtest

### ISSUE THREAD

**Issue by goooseman** [quarckster/kodi.kino.pub#39]
На сайте kino.pub есть очень полезный speedtest (https://xxx/speed). Им удобно пользоваться перед просмотром видео, чтобы точно знать, что можно себе позволить 4K или хотя 1080p (хотя на самом деле вроде скорости должно хватать, но в итоге не обходится без буферизаций, но это уже другая история).

Насколько сложно реализовать этот функционал в рамках этого плагина?
Я готов за это взяться, если будет какой-то высокуровневый план что куда писать, ибо я с разработкой Kodi плагинов и Python очень мало знаком.

Энивэй, где можно посмотреть документацию к кинопабу? Или приходится самим изучать, что приходит?

Я конечно сделал примерный анализ, как это работает в веб версии:

1. Делается запрос к `getIp?r=0.1635698979384903`, в ответ с заголовком `Content-Type: text/html` содержится просто IP адрес одной строкой, например: `37.122.157.150`, что странно, ибо это не html. Причем сам запрос идет на IP `138.201.252.152`.
2. Делается 13 запросов одновременно к `garbage.php?r=0.42050030208790745&ckSize=20` с разными значениями query параметра `r`. Самое интересное - запросы идут на ip `138.201.252.152`, то есть не на айпишник, полученный в запросе `getIP`, а просто зарезолвленный по DNS. Ответ с заголовком `Content-Type: application/octet-stream` содержит в себе бинарные данные, а именно файл с именем `random.dat`. Максимальный размер файлов - 20MB. Но вообще разнятся от 1-о до 20-и.
3. Делается ~40 запросов одновременно к `empty.php?r=0.21317927611116927` с разными значениями query параметра `r`. IP всё так же `138.201.252.152`. В ответ приходит `Content-Type: text/html` с пустым body.
4. Повторяются шаги 1, 2, 3 только для поддоменов `nl-speed` и `ru-speed` соответственно.

Судя по всему, `empty` запросы нужны для симуляции загрузки сети, а вот `garbage` явно для замера скорости. Зачем нужен `getIP`, который все равно больше нигде не используется - я не понимаю.

**Comment by quarckster** [comment]
Официальная документация API не даёт никакой информации о тесте скорости https://kinoapi.com/. Так что остаётся реверс-инжиниринг описанный вами.

**Comment by goooseman** [comment]
Ok, на самом деле вроде бы ничего сложного.
Глянул js сырцы скрипта, который делает это в вебе (сохранил его в [гисте](https://gist.github.com/goooseman/9730b1df891d292a708d1d885160b0e1) для удобства). Что узнал:
1. `getIP` запрос возвращает ip адрес клиента. 
2. Query параметр `r`, что присутствует в каждом запросе - чистый рандом (`Math.random()`). И нужен для того, чтобы браузер не кэшировал ответ сервера.
3. Скрипт по дефолту (без доп настроек для разных браузеров) делает 10 потоков на download и 3 на upload (вот этого я не знал, в интерфейсе отображается лишь скорость download, да и функционирования сервис скорость upload вообще же не важна)
4. Скрипт делает и upload и download одновременно на протяжении 15-и секунд ровно. Сколько скачалось, столько и скачалось - остальные соединения скрипт режет по истечению таймаута.
5. Куча запросов к `empty` - это ping тест. Делает 35 запросов для этого теста.

Вообще за основу взят open source [HTML5 speedtest](https://github.com/adolfintel/speedtest/) библиотека, о чем говорится в начале файла.

Если глянуть на [тестовую страницу библиотеки](http://speedtest.fdossena.com) становится очевидно, что она умеет показывать и IP клиента (запрос `getIp`) и скорость upload (3 подключения на upload) и ping и jitter (запрос `empty`). Но на сайте кинопаба эта информация не показывается, показывается только скорость download.

То есть я к тому, что просто download теста будет достаточно.
Так что план минимум по этому таску следующий:

1) Сделать пункт в меню "Спидтест"
2) При нажатии открывается страница, на которой написана скорость по трем серверам (по дефолту по нулям) и кнопка "Начать". При ее нажатии начинается тест.
3) Делается 10 запросов к `garbage` с рандомным query провайдером `r` (может у Коди и нет кэша на HTTP запросы, но хуже не будет) и параметром `ckSize` равным 20-и (размер чанков). Постараюсь сделать realtime обновление счетчика.
4) Через 15 секунд рвем соединения, подсчитывается среднюю скорость, отображается в счетчике.
5) Повторяются шаги 3-4 для остальных серверов.

Как вам такой план? Могу скоро приступить к реализации.

**Comment by quarckster** [comment]
Отличный план, буду рад новой фиче.

**Comment by catbaxter** [comment]
Всем привет, я разработчик Андроид версии, могу подкинуть пару идей.

1. Просьба убрать из обсуждения все линки :) Это не моя просьба...
2. Спидтест надо проводить imho на конкретном фильме и по hls2 протоколу, т.к. mp4 имеет ограничение по скорости (4.5 мб.с ~ 36 Мбит.с)

**Comment by goooseman** [comment]
@catbaxter привет
Вот так вот удалил, нормально?

А что за ограничение скорости по http? Это на стороне сервера? И как тогда 4К видео играют при HTTP потоке?

**Comment by catbaxter** [comment]
Салют, на кинопаб тоже плз линки почисти, чтобы вообще не ясно было

**Comment by catbaxter** [comment]
> @catbaxter привет
> Вот так вот удалил, нормально?
> 
> А что за ограничение скорости по http? Это на стороне сервера? И как тогда 4К видео играют при HTTP потоке?

Да, на стороне сервера ограничение, 4к очень разняться по битрейту - есть и по 5 мбит.с, есть по 40 - эти будут по http (mp4) всегда тормозить

**Comment by goooseman** [comment]
@catbaxter done

Если делать тест по конкретному видео, то как реализовать проверку скорости на всех серверах (Германия/Россия/Нидерланды)?

Мне же API возвращает уже готовую ссылку на фильм только на выбранном мной сервере.

**Comment by catbaxter** [comment]
> @catbaxter done
> 
> Если делать тест по конкретному видео, то как реализовать проверку скорости на всех серверах (Германия/Россия/Нидерланды)?
> 
> Мне же API возвращает уже готовую ссылку на фильм только на выбранном мной сервере.

в декабре какую удобную штуку сделали - к ссылке можно прицепить серевер параметром, например

?loc=de

и после замеров через API можно выставить настройку глобально для дальнейшего использования

**Comment by goooseman** [comment]
@catbaxter спасибо. Есть ли информация какой скорости хватит для какого качества плюс/минус?
Мне же потом надо написать пользователю, ваша скорость такая-то, рекомендуем такое-то качество.

**Comment by catbaxter** [comment]
По идее, если выставлен hls4 - то для минимального качества нужен всего 1 мбит.с и спидтест как бы и не нужен вообще :) Но это в теории - на практике получается, что верхняя граница качества в hls4 манифесте очень 'гуляет' - т.е. там прописано фиксированно 5 мбит.с (для 1080p) и 12 мбит.с (для 4K) но на практике битрейт может доходить и до 10 мбит.с у 1080 и до 40 мбит.с у 4k. Как замерять - берем фильм и по идее начинаем сгружать чанки из манифеста один за другим (еще и лучше с места остановки просмотра :) - hls2 в принципе еще и лучше, т.к. видео уже со звуком (а не отдельно, как в hls4). В манифесте у чанка есть его длительность:

#EXTINF:12.000,
https://....../seg-1-v1-a1.ts

т.е. можно вычислить битрейт чанка по его длине и времени плюс скорость скачивания, что дает нам очевидную картинку скоростных показателей пользователя для _конкретного фильма_.

**Comment by goooseman** [comment]
@catbaxter еще вопрос уже касательно просто функционирования сервиса

Просто у меня не супер работает он (а именно появляются буферизации) на 1080p (и на 720p, но уже лучше), что в Kodi, что в приложении под Android.

Я использую HTTP поток везде, так как на сайте сказано, что это единственный способ выбирать аудиодорожку и субтитры.
Но выходит, что HLS4 при любом раскладе лучше и быстрее в плане оптимизации видео.

Я так вижу, что в HLS4 видео идет отдельно от звука, так может быть можно как то реализовать выбор аудиодорожки и субтитры в этом режиме потока?

**Comment by catbaxter** [comment]
Ну, естественно, hls4 - это наше все и выставлено по умолчанию во всех приложениях. Мало того, только в hls4 можно выбирать сабы (к mp4 тоже можно прилепить отдельно), так hls4 - адаптивен (т.е. выбирает качество видео в зависимости от скорости соединения), плюс стартует быстро, плюс  тащит только то аудио, что в данный момент что нужно пользователю, а не все аудиодорожки, как в mp4

**Comment by catbaxter** [comment]
Собственно в андроид приложении аудиодорожки и субтитры выбираются только в hls4 (в mp4 - можно выбрать только дорожки а сабы надо подгружать отдельно перед стартом плеера)

**Comment by quarckster** [comment]
hls4 не поддерживается в Kodi

**Comment by catbaxter** [comment]
Фигово, мне кто-то говорил, что поддерживается, может, перепутал

**Comment by goooseman** [comment]
Меня вопрос протокола очень сильно интересует, так как использовать более оптимизированный протокол для меня было бы очень кстати, ибо до нашей деревени HTTP поток в 1080p долетает очень плохо.

Вопрос лишь в том, действительно ли может быть bottle neck в этом месте, но если есть информация о том, что HTTP потом искусственно ограничен, то я решил разобраться с поддержкой HSL4.

Вероятно эту дискуссию стоит переносить в отдельное issue, если действительно есть возможность реализовать просмотр через HSL4 поток. Я понимаю, что по сравнению с HSL2 нет никакого прироста в скорости, ибо контейнер то один и тот же, но с HSL2 мы теряем выбор аудиодорожки (судя по информации на кинопабе), поэтому для меня эта тема важна.

Я пошел почитать вообще про HSL и про разницу в протоколах.
HSL4 отличается от предыдущей версии следующим:

- Segments with bit range support with tag EXT-X-BYTERANGE
- Support for fast forward and fast rewind with tags EXT-X-I-FRAMES-ONLY and EXT-X-I-FRAME-STREAM-INF
- Alternate media option with tag EXT-X-MEDIA (я так понимаю, это самое важное для нас, то есть в плейлисте есть сразу все варианты видео, и становится возможен адаптивный выбор качества)

Я пошел почитать [сырцы текущей версии реализации hls в ffmpeg](https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/hls.c) и там есть поддержка всех этих тегов (добавлена еще в 2014-м).

Плюс на [странице документации ffmpeg](https://ffmpeg.org/ffmpeg-formats.html) в разделе `hls_flags` в разделе `single_file` есть следующее сообщение: `HLS playlists generated with this way will have the version number 4`. То есть генерацию HLS плейлиста версии 4 он явно поддерживает.

Я пока что дальше не буду копать, так как могу много не понимать и в разработке Kodi плагина совсем еще зеленый, но, если все таки есть шанс, что оно все таки поддерживается, готов с радостью продолжить research на эту тему в рамках отдельного issue. А в этом вернусь к реализации спидтеста.

**Comment by quarckster** [comment]
В kodi 18.2 hls4 стал работать.

**Comment by goooseman** [comment]
Ух, я в итоге перешёл на Plex, так как устал от коди
