### ISSUE TITLE
Importing movies and tvshows into kodi library?

### ISSUE THREAD

**Issue by Kampfader** [quarckster/kodi.kino.pub#4]
can u make this Option for kino.pub addon

Creates .strm files with urls to kinopub plugin.
Additionally generates .nfo files, or scraping from thetvdb, themoviedb etc.

Thanks

**Comment by Kampfader** [comment]
у меня кино.пуб версия есть где это функция интегрированная, это версия от "TroRg" вот этот я в ручную добавил https://github.com/TroRg/kodi.kino.pub/pull/4 как @quarckster сделал https://github.com/TroRg/kodi.kino.pub/pull/13 больше не идёт.


[video.kino.pub.zip](https://github.com/quarckster/kodi.kino.pub/files/2488659/video.kino.pub.zip)

**Comment by Kampfader** [comment]
Ну что ребята, ни у кого нету настроения или желания,  сделать эту функцию?

**Comment by quarckster** [comment]
Я вижу здесь проблему. Если мы реализуем эту фичу, и когда-нибудь поменяем урлы в плагине, то все эти импортрованные strm файлы превратятся в тыкву.

**Comment by VyacheslavTeplyakov** [comment]
Зато до этого момента, который может и не произойти, все будет выглядеть просто шикарно.

**Comment by quarckster** [comment]
@VyacheslavTeplyakov буду рад пулл реквесту от вас.

**Comment by Limeone** [comment]
[AddToLib](http://xbmc.ru/forum/showthread.php?t=12708) прекрасно справляется с этой задачей

**Comment by Kampfader** [comment]
Прошло патчи два Года, у меня установлена старая версия кино.пуба.
Где это функция работает. Но, После Kodi19(Python3) больше не бутит ;)

Ребята, где этот Мастер?
Пора добавить это и в Новую версию...

**Comment by quarckster** [comment]
мастер ещё не переведён на python3, и указали же на  AddtoLib

**Comment by Kampfader** [comment]
тестировал я AddtoLib
Каждый рас надо прописывать в ручную имя Фильма, автоматом, делает вот так.
"где.моя.челюсть,.чувак.war.with.grandпа.strm"

А Сериалы вообще можно забыть.

**Comment by quarckster** [comment]
Я в этой фиче не заинтересован, но с удовольствием рассмотрю PR.
