### ISSUE TITLE
Kodi Leia (final): статусы видео отображаются некорректно после любого действия с элементом списка.

### ISSUE THREAD

**Issue by vevsvevs** [quarckster/kodi.kino.pub#43]
На первый взгляд похоже на [эту проблему](https://github.com/quarckster/kodi.kino.pub/issues/26), но теперь всё хуже, т.к. слетают отметки всех элементов: реальные статусы показывает только при первом формировании списка, если же совершить любое действие (воспроизведение, отметить как.., изменить закладки) - все элементы списка становятся непросмотренными вплоть до обновления списка (т.е. помогает перезайти в папку). 
Пробовал добавлять `Container.Refresh` в плеере, но тогда опять приходится мириться со потерей  фокуса (слетает на первый элемент списка) и задумчивостью при остановке воспроизведения.
Началось это с месяц назад, в одной из очередных бет Kodi, думал к финалу откатят - не случилось. Наверное, разработчики пытаются что-то улучшить, но по результату - пользоваться стало крайне неудобно :(

**Comment by quarckster** [comment]
Тоже столкнулся с такой проблемой. Попытался починить в https://github.com/quarckster/kodi.kino.pub/commit/ab0ec254be3d95adf644bf0f2e58bb2c064c0655. На моём kodi работает.

**Comment by vevsvevs** [comment]
Большое спасибо, что не бросили :) Насколько могу судить - теперь всё отлично работает!
