### ISSUE TITLE
(Settings) Reset auth, not disable after restart the addon

### ISSUE THREAD

**Issue by Kampfader** [quarckster/kodi.kino.pub#5]
should only be activated once, after the next start it should be automatically deactivated again..

**Comment by quarckster** [comment]
@Kampfader  Can you please provide detailed steps to reproduce? What are the actual results and the expected results?

**Comment by Kampfader** [comment]
not working..

i have fresh install Kodi and the new 2.0.2 kino.pub

and make two debug logfiles, the first one is the first start of kino.pub addon

https://pastebin.com/uExVDCf6 - No Bug, first Start, first auth after fres install.

https://pastebin.com/nc2t17L9 - Bug, second start, with enable "сбросить авторизацию"

**Comment by quarckster** [comment]
Я не могу воспроизвести баг. Аутентификация проходит только один раз, когда я нажимаю "Сбросить авторизацию".

**Comment by Kampfader** [comment]
Интересно..
Я сегодня после работы попробую сделать короткое видео..

**Comment by Kampfader** [comment]
добавил видео, и вопрос аддон на версии 2.0.0, в коем случая в Коди так стоит.

**Comment by quarckster** [comment]
Я исправил версию аддона, но баг так и не могу воспроизвести. Мои шаги:
1. устанавливаю плагин
2. выполняю аутентификацию плагина
3. плагин аутентифицируется
4. иду в настройки и сбрасываю аутентификацию
5. повторяю пункт 2

бага нет

**Comment by Kampfader** [comment]
попробуй после 4. пункта, перегрузить Коди..
какая версия от Коди стоит?

**Comment by quarckster** [comment]
После перезапуска kodi баг всё так же не воспроизводится. Kodi 17.6. Попробуй удалить каталог `%APPDATA%\kodi\userdata\addon_data\video.kino.pub`

**Comment by Kampfader** [comment]
поставил Коди 17,6 тоже нету бага, тогда решили, что проблема с Коди 18.

на Коди 18 я папку "%APPDATA%\kodi\userdata\addon_data\video.kino.pуб" удалял тоже..
