### ISSUE TITLE
Отображение чья озвучка в плеере (Кубик в кубе, дубляж и тд)

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#51]
Проверил на сериале The Boys, имеются 6 озвучек, но не известно / понятно где какая.

Заранее спасибо.

**Comment by quarckster** [comment]
Не уверен, что плагин здесь может как-то помочь. Насколько я знаю, kodi берёт эту информацию из метаданных видеофайла или потока.

**Comment by fallenfuzz** [comment]
Понял, спасибо.
Жаль, когда 6 озвучем, не понятно где чья.

**Comment by fallenfuzz** [comment]
Оно вроде должно отдавать название озвучки судя по API, можешь плиз посмотреть если можно прикрутить для коди?
 "audios": [
                   {
                       "id": 15510,
                       "index": 1,
                       "codec": "aac",
                       "channels": 2,
                       "lang": "ukr",
                       "type": {
                           "id": 2,
                           "title": "Многоголосый",
                           "short_title": "MVO"
                       },
                       "author": {
                           "id": 7,
                           "title": "Дохалов",
                           "short_title": null
                       }
                   },
                   {
                       "id": 15504,
                       "index": 2,
                       "codec": "aac",
                       "channels": 2,
                       "lang": "rus",
                       "type": {
                           "id": 2,
                           "title": "Многоголосый",
                           "short_title": "MVO"
                       },
                       "author": {
                           "id": 1,
                           "title": "Видеосервис",
                           "short_title": null

**Comment by quarckster** [comment]
Да, но куда эту информацию в коди передать? Здесь нет такого тэга https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14

**Comment by fallenfuzz** [comment]
Возможно ли смерджить в 
language | string (en) ?

**Comment by fallenfuzz** [comment]
я помнул что где-то видел и работало, так вот, плагин кинопоиск с использованием движка ТАМ
https://imgur.com/lqp9itF

**Comment by fallenfuzz** [comment]
ping ☺

**Comment by quarckster** [comment]
Пока не вижу возможности, как это реализовать. Если есть идеи,то можете оформить PR

**Comment by fallenfuzz** [comment]
:( к сожалению далёк от этого.

**Comment by fallenfuzz** [comment]
@Limeone вот это было бы совсем круто сделать :)
Зарабее спасибо.

**Comment by Limeone** [comment]
@fallenfuzz не думаю что kodi так умеет
[addStreamInfo](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#gaf0c020ba8bc205d61e786dfec9111cdc) на сколько я понял, kodi принимает значение сроки языка в формате ISO639

**Comment by fallenfuzz** [comment]
> @fallenfuzz не думаю что kodi так умеет
> [addStreamInfo](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#gaf0c020ba8bc205d61e786dfec9111cdc) на сколько я понял, kodi принимает значение сроки языка в формате ISO639

как они тут сделали? Я в этом не понимаю, возжно дасть direction, так сказать.

кинопоиск с использованием движка ТАМ
https://imgur.com/lqp9itF

**Comment by Limeone** [comment]
> > @fallenfuzz не думаю что kodi так умеет
> > [addStreamInfo](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#gaf0c020ba8bc205d61e786dfec9111cdc) на сколько я понял, kodi принимает значение сроки языка в формате ISO639
> 
> как они тут сделали? Я в этом не понимаю, возжно дасть direction, так сказать.
> 
> кинопоиск с использованием движка ТАМ
> https://imgur.com/lqp9itF

я их кода не видел, и не знаю что они делали. и даже на знаю о каком плагине идет речь

**Comment by fallenfuzz** [comment]
@Limeone sorry, конечно - 
ТАМ - http://xbmc.ru/forum/showthread.php?t=15920
кинопоиск - http://xbmc.ru/forum/showthread.php?t=14790
Вот

**Comment by quarckster** [comment]
В коде TAM разобраться невозможно, это набор каких-то ужасных костылей из лапшекода.
