### ISSUE TITLE
Отображение imdb рейтинга и года выпуска после / до именни фильма / сериала 

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#52]
Carnival Row [8.1] и цвета можно добавить, меньше 5 красное, 5-7 жёлноте, 7+ зелёное.
на пример.

Спасибо

**Comment by stavultras** [comment]
А это не тоже самое https://github.com/quarckster/kodi.kino.pub/issues/23?

**Comment by fallenfuzz** [comment]
> Отображение где именно?
> 
> Подобное было: #23 и #25

Тут слегка другое.
Спасибо

**Comment by quarckster** [comment]
Хотел бы вообще избегать цветов, это довольно субъективная вещь. Кому-то может не понравится.

**Comment by fallenfuzz** [comment]
Понимаю, но ети очень удобно :)
Сразу видно что фуфу, а что кое-как можно смотреть.
Ну и год в названии тоже оч. полезно.

Заранее спасибо.

**Comment by fallenfuzz** [comment]
Можно ли открыть?
И подумать как добавить без цветов такое?
Очень не хватает. 

Спасибо

**Comment by quarckster** [comment]
шлите патчи, я не заинтересован.
