### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#53]
Сортировка в плагине заметно отличаетса с сайтом.
Можно ли сделать так же как на сайте ?

Заранее спасибо.

**Comment by quarckster** [comment]
Сортировка в плагине такая же как в API. Насколько я знаю, сайт кинопаба работает не через то же API, что и плагин, в этом скорее всего и заключается различие.

**Comment by fallenfuzz** [comment]
а через какой АПИ работает сайт?
Странно что их несколько, для плагина один, для сайта другой.

Можно ли сделать как на сайте? Там фильтр оч, удобый.

**Comment by quarckster** [comment]
Я не знаю через какой апи работает сайт, но не похоже, что через три же
что плагин и другие приложения. Сделать кастомную сортировку в плагине коди
проблематично. В коди есть своя сортировка, которая оперирует с уже
отрендеренными элементами. То есть задать сортировку в плагине через
сортировку коди на получится.

вс, 29 сент. 2019 г., 14:40 fallenfuzz <notifications@github.com>:

**Comment by fallenfuzz** [comment]
https://kinoapi.com/api_video.html#video - тут этот api?
Есть сортировка, всё кошерно :)
Я не девелопоер, можешь посмотреть?

**Comment by quarckster** [comment]
Как ты предлагаешь реализовать сортировку в UI? Где должна быть эти кнопки?

**Comment by fallenfuzz** [comment]
внутри фильмы, сериалы и тд, не?
Там же сейчас есть

Последние, популярные - они как Shortcuts я так понимаю, правильно? 
Можно ли вместо сделать сортинг?

Думаю достаточно будет

created
updated
rating
views
watchers

**Comment by fallenfuzz** [comment]
ping ☺

**Comment by fallenfuzz** [comment]
Вопрос остаетса открытым.
Есть ли возможность переделать / улучшить поиск?

Спасибо
