### ISSUE TITLE
request: Thumbnails в закладках

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#54]
Доброе время суток.
Можно ли сделать Thumbnails в закладках такого-же размера как и в, скажем, "Я смотрю"?
А то очень уж они мелкие в закладках.

Заранее спасибо.

**Comment by quarckster** [comment]
Можно просто выбрать другой viewtype в настройках отображения списка.

**Comment by fallenfuzz** [comment]
Можно да, но нужно именно Thumbnails , а тогда картинки маленькия.
В "Я смотрю" с размером всё хорошо.
Вот и поинтересовался если можно сделать размер картинок в закладках для viewtype Thumbnails , такой-же как и в  "Я смотрю".
