### ISSUE TITLE
bug? Закладки и сериалы

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#56]
Добрый день / ночь / вечер,

Обратил внимание что если добавить в закладки сериал, то просмотренные серии исчезают если их обратно не отметить как не просмотренное на сайте.

Можно-ли это поменят? возможно через кастройки?
Очень неудобно особенно детям когда хотят пересмотреть уже посмотренные серии.

Спасибо.

**Comment by quarckster** [comment]
Нужны подробности. У меня в закладках есть сериалы, серии никуда не исчезают.

**Comment by stavultras** [comment]
Очень похоже на пункт "Я смотрю", а не на закладки. У меня из обычных закладок тоже никуда не исчезает.

**Comment by fallenfuzz** [comment]
Странно, дети смотрят Фиксики и когда серия заканчиваетса сама, просмотренная ичезает из списка, Имя закладки на русском если что.
Если я пойду на сайт, выберу всё что просмотренно и верну в не просмотренное, появитса в закладках обратно.

Накидать скиншотов? 

В  "Я смотрю" серии не пропадают, а выделяутся как просмотренные.
