### ISSUE TITLE
Не получается сменить звуковые дорожки

### ISSUE THREAD

**Issue by tupizm** [quarckster/kodi.kino.pub#58]
Оборудование Андроид приставка H96Max
По рекомендации на сайте менял поток на http, но при запуске фильма программа зависает. На остальных типах потока сменить дорожку не получается

**Comment by stavultras** [comment]
@tupizm программа Kinopub для Anroid? Если да, то вам не сюда, тут про плагин для Kodi.

**Comment by tupizm** [comment]
В плагине

**Comment by stavultras** [comment]
@tupizm понял, на AlexELEC/CoreELEC + Kodi + Kinpub такой проблемы не наблюдается. Подозреваю что проблема в самом Андроиде на вашем желе, либо в Kodi.

**Comment by tupizm** [comment]
Да, менял только в плагине. А что такое  AlexELEC/CoreELEC?

**Comment by stavultras** [comment]
@tupizm альтернативная ОС на Linux, в которой собсно только Kodi и есть.
Но H96Max вроде на рокчипе, а под него *Elec вроде нормальных нету пока ещё.

**Comment by tupizm** [comment]
А на сайте HLS4 оставить? И все остальные галки? или может SSL какой-нибудь может влиять

**Comment by stavultras** [comment]
@tupizm у меня на сайте стоит HTTP (но было и HLS4, тоже работало - я думаю эти настройки влияют только на просмотр контента через браузеры) + SSL (галки вроде по-умолчанию все)

**Comment by tupizm** [comment]
Скорей всего приставка, тогда. Попробую на телефоне сделать - посмотрю, как там отработает

**Comment by stavultras** [comment]
@tupizm на всякий случай проверил на Windows + Kodi 18.5 + последняя версия плагина. В плагине поставил HTTP, на сайте - HLS4 (по-умолчанию) - дорожки переключаются без проблем.

**Comment by tupizm** [comment]
Интересно. Поставил на телефоне, и заметил интересную штуку. Южный парк заработал нормально, дорожки меняются а большие фильмы не хочет. Попробовал Гарри Поттер, Назад в будущее, Монстро и ни один не запустился даже. Сейчас тоже самое попробую на приставке
