### ISSUE TITLE
Пропал режим просмотра разделов «значки».

### ISSUE THREAD

**Issue by apazhe** [quarckster/kodi.kino.pub#6]
Тот, в котором показывались рядами мелкие обложки сериалов с подписанным под ними названием и кол-вом непросмотренных.

Самый удобный режим для обзора «я смотрю».

Причём сразу после обновления с предыдущей версии плагина он был, но пропал после первого же переключения режима просмотра раздела.

**Comment by apazhe** [comment]
Вот, например, как выглядит аналогичный режим в плагине soap4.me.
![screenshot275](https://user-images.githubusercontent.com/20211341/46828169-3bb6d000-cda3-11e8-8c47-362d862af82f.png)

**Comment by quarckster** [comment]
Это произошло из-за этой строчки https://github.com/quarckster/kodi.kino.pub/blob/master/resources/lib/addonworker.py#L362. Здесь плагин сообщает Коди, что в этой папке содержатся сериалы, и Коди настраивает внешний вид в соответствии со своими настройками.

**Comment by apazhe** [comment]
Ну то есть вы это устраните?

**Comment by quarckster** [comment]
Я конечно мог бы убрать эту строчку, но тогда пропадут другие режима просмотра. Так что это не совсем баг.

**Comment by apazhe** [comment]
А как же оно раньше всё работало?

**Comment by quarckster** [comment]
раньше этой строчки не было

**Comment by apazhe** [comment]
А нельзя ли как-то и рыбку съесть и…

**Comment by apazhe** [comment]
Или можно закомментить эту строчку и всё исправится?
