### ISSUE TITLE
автовоспроизведение следующего видео. v2.8.0-beta1

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#61]
Не работает :(

В настройках коди выставить "Auto play next video".

**Comment by Kampfader** [comment]
Наводим на 1 эпизод или фильм,  нажимаем на кнопку "C", Затем откроется меню там выбираем "Play from here".
После этого у вас будет автоматически переключаться видео.
Я так всегда включаю короткие мультфильмы

**Comment by fallenfuzz** [comment]
@Kampfader Спасибо. Попробую.

**Comment by fallenfuzz** [comment]
@quarckster а почему закрыл?
У меня никак не работает.

@Kampfader у вас coreelec?

**Comment by quarckster** [comment]
Потому что это к плагину отношения не имеет.

ср, 11 дек. 2019 г., 19:33 fallenfuzz <notifications@github.com>:

**Comment by Kampfader** [comment]
Coreelec 9.2.1
Картинке нету, так как я снемал с ПС (VNC)
![pic](https://user-images.githubusercontent.com/23200748/70653497-df746800-1c54-11ea-8ef6-8d9f007322f5.gif)

**Comment by fallenfuzz** [comment]
@Kampfader хм, а на чем елек? у меня на миниксе + сдкарт, и не работает :(

**Comment by fallenfuzz** [comment]
[http://paste.kodi.tv/lucoribuxe.kodi](LOG)
@quarckster не понятно причём тут plugin.video.elementum

**Comment by fallenfuzz** [comment]
@Limeone не могли бы вы вы глянуть на лог плз?
Спасибо

**Comment by Limeone** [comment]
@fallenfuzz я PR создал, дальше решение за  @quarckster 
https://github.com/quarckster/kodi.kino.pub/pull/65
