### ISSUE TITLE
Хотелка: больше 20 элементов на странице.

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#64]
Когда много фильмов в закладке, 100 скажем, очень не удобно перелистывать по 20.
Если можно в настойки вынести скажем 20,40,60,80,100 на выбор - было-бы волшебно.

Заранее спасибо

**Comment by fallenfuzz** [comment]
@Limeone, а что насчет этого думаешь? :)

**Comment by Limeone** [comment]
Ну, это реально, я у себя попробовал, не уверен что большие списки не будут подтормаживать на слабых девайсах. У меня на raspberry pi 3 и с 20 элементами долго думает6

**Comment by fallenfuzz** [comment]
@Limeone для этого в настройки и выносится.
Ну а если не делать и оставить по 20, сделать кнопку "back to first page" или "back to main page" на кажной странице, а то на пульте "back" не листает назад страницу, а выкидывает из плагина, и если страниц 5 перелистал, приходиться листать обратно все 5 чтоб в мэйн попасть.

Заранее спасибо.

**Comment by Limeone** [comment]
А что за девайс? Это не плагин, это так пульт так настроен (или чем вы так пользуетесь)

**Comment by fallenfuzz** [comment]
LG magic remote

**Comment by Limeone** [comment]
В kodi для удобства перенастройки кнопок пультов есть плагин Keymap Editor

**Comment by quarckster** [comment]
Стоит сказать, что с увеличением эелементов на странице линейно будет возрастать время на её отображение. В некоторых списках необходимо на каждый элемент отдельный запрос к API делать.

**Comment by quarckster** [comment]
> @Limeone для этого в настройки и выносится.
> Ну а если не делать и оставить по 20, сделать кнопку "back to first page" или "back to main page" на кажной странице, а то на пульте "back" не листает назад страницу, а выкидывает из плагина, и если страниц 5 перелистал, приходиться листать обратно все 5 чтоб в мэйн попасть.
> 
> Заранее спасибо.

Мне кажется проще добавить отдельную кнопку "Домой" в конец списка, чтобы не листать обратно долго. Большое количество элементов будет сильно долго отображаться.

**Comment by fallenfuzz** [comment]
> > @Limeone для этого в настройки и выносится.
> > Ну а если не делать и оставить по 20, сделать кнопку "back to first page" или "back to main page" на кажной странице, а то на пульте "back" не листает назад страницу, а выкидывает из плагина, и если страниц 5 перелистал, приходиться листать обратно все 5 чтоб в мэйн попасть.
> > Заранее спасибо.
> 
> Мне кажется проще добавить отдельную кнопку "Домой" в конец списка, чтобы не листать обратно долго. Большое количество элементов будет сильно долго отображаться.

как вариант, да, можно.
Спасибо!
