### ISSUE TITLE
Трейлеры фильмов в Coreelec и Libreelec

### ISSUE THREAD

**Issue by Sheredeka** [quarckster/kodi.kino.pub#66]
Очень бы хотелось иметь возможность просмотра трейлеров для фильмов.
На данный момент пробовал использовать Coreelec и Libreelec. Результат в логе:

NOTICE: [video.kino.pub]: sending GET request to http://api.service-kp.com/v1/items/trailer?id=59785
NOTICE: [plugin.video.youtube] Running: YouTube (6.5.2) on Leia (Kodi-18.5) with Python 2.7.16
                                            	Path: /
                                            	Params: {'action': 'play_video', 'path': '/root/video', 'videoid': '59785'}
WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?path=/root/video&action=play_video&videoid=59785"
WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=59785"

**Comment by Limeone** [comment]
а где ошибка то? выглядит так что в плагине [ютуба](https://github.com/jdf76/plugin.video.youtube/blob/d8fac70688d768c54871a0f635919d914163b6e6/resources/lib/youtube_plugin/youtube/helper/yt_old_actions.py) поменяли пути и просят разрабов сторонних плагинов тоже их поменять по возможности.  Но именно ошибки в логе нету

**Comment by Sheredeka** [comment]
Обновился video.kino.pub до версии 2.8.0 - проблема ушла. Спасибо!
