### ISSUE TITLE
Разъяснение по поводу типа стриминга.

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#69]
Привет,
в настройках плагина:
http
hls
hls2
hls4

на сайте 
http
hls2
hls4 (рекомендуемое и выбрано)

Пробовал в плагине hls4 поставить, 1080p завелось, 4К нет :(
вернул http - заработал 4К

Где истина? :)
Что рекомендуется выбирать в плагине <-> сайте?

Заранее спасибо.

**Comment by Sheredeka** [comment]
Присоединяюсь! Было бы очень круто, если бы настройки содержали в себе выбор стриминга в опции выбора качества - не пришлось бы мотать список при запуске фильма. Выбрал http - получил короткий список только из http потоков. Сейчас же приходится искать золотую середину, к которой как раз находятся "http 720p" и "http 1080p"

**Comment by quarckster** [comment]
На сайте выбрать можно поток по умолчанию, это если в клиенте не реализован выбор потока. Но в плагине мы явно задаём тип потока какой нам нужен. Так что настройки потока на сайте не влияют на плагин. Единственное, что влияет это расположение cdn сервера, откуда будет отдаваться контент.

**Comment by fallenfuzz** [comment]
@quarckster спасибо.
А что рекомендуется выбрать в плагине с выбором аудио дорог и субтитрами, и 4к?

**Comment by quarckster** [comment]
http и hls4.

**Comment by fallenfuzz** [comment]
@quarckster спасибо! попробую.
