### ISSUE TITLE
Идея: Можно ли вынести выбор озвучки при входе в серию?

### ISSUE THREAD

**Issue by fallenfuzz** [quarckster/kodi.kino.pub#72]
или в настройки с выставлением приоритетов?

**Comment by fallenfuzz** [comment]
или в настройки с выставлением приоритетов?

**Comment by quarckster** [comment]
Насколько я понимаю ничего с озвучкой сделать нельзя. Kodi берёт имена дорожек из потока, если в файле или потоке дорожки имеют имена, то Kodi их покажет. Kino.pub в API присылает метаданные об аудио, но нет возможности в самом Kodi поменять имя дороги.
