### ISSUE TITLE
не работает выбор звуковой дорожки

### ISSUE THREAD

**Issue by RusAlex** [quarckster/kodi.kino.pub#74]
последняя версия

**Comment by quarckster** [comment]
Такие баг-репорты ни о чём не говорят. Нужны конкретные номера версий и kodi в том числе. Дальше необходимо описать подробные шаги для воспроизведения.

**Comment by RusAlex** [comment]
понял. 

18.5 Git:20191208-b9f4eaad0a-dirty Media Center Kodi (из raspbian buster репозитария) 

video.kino.pub-2.8.1.zip

выбрать любой фильм и попробовать переключить дорожку

**Comment by quarckster** [comment]
Не могу воспроизвести. Открываю любой фильм, иду в настройки аудио и вижу там много дорожек, могу переключать. Более того, плагин к выбору аудиодорожек отношения не имеет. Задача плагина, просто скормить ссылку с потоком Kodi, на этом его работа закончена.
