### ISSUE TITLE
Автостарт следующей серии автоматически (в сериалах и т.п)

### ISSUE THREAD

**Issue by nikoify** [quarckster/kodi.kino.pub#75]
Есть ли возможность добавить такую функцию в настройки плагина?
Знаю что kodi может так делать с локальными файлами, но с онлайновыми это уже совсем другое.
Уважаемый разработчик возможно ли добавить такой функционал?

**Comment by quarckster** [comment]
Всё работает точно так же. Выбираете серию и через контекстное меню "Play from here".
