### ISSUE TITLE
Не работает переключение аудиодорожек и поиск

### ISSUE THREAD

**Issue by allmazz** [quarckster/kodi.kino.pub#77]
**Доступна только одна аудиодорожка**
Не получается переключится на другую озвучку. Стоит `Kodi from Debian 17.6`. Проблема на всех моих устройствах. Версия плагина от второго Февраля `2.8.1`.
**Не работает поиск**
При нажатии кнопки `Поиск`(не важно в общем поиске, в фильмах, сериалах и т.д). Приходиться в приложении добавлять фильм в `Я смотрю` и потом из этого списка включать в Kodi. Стоит `Kodi from Debian 17.6`. Проблема на всех моих устройствах. Версия плагина от второго Февраля `2.8.1`.

**Comment by stavultras** [comment]
А тип потока у вас какой? У меня на HTTP потоке переключаются дорожки без проблем. На других не пробовал.

**Comment by allmazz** [comment]
> А тип потока у вас какой? У меня на HTTP потоке переключаются дорожки без проблем. На других не пробовал.

HLS щас попробую HTTP. У Вас поиск работает?

**Comment by quarckster** [comment]
HLS поддерживает толкь одну дорожку, используйте HLS4. Предварительно установитье inputstream.adaptive.

**Comment by allmazz** [comment]
Спасибо огромное. А поиск?

**Comment by quarckster** [comment]
Для каждой проблемы необходимо создавать отдельный issue.

**Comment by stavultras** [comment]
Поиск работает, запускается прям из выдачи результатов. Но один фильм не запустился, но я думаю это проблема самого кинопаба.
