### ISSUE TITLE
Не работает поиск

### ISSUE THREAD

**Issue by allmazz** [quarckster/kodi.kino.pub#78]
Не работает поиск(глобальный, только по фильмам, сериалами и т.д т.п) Стоит `Kodi from Debian 17.6`. Проблема на всех моих устройствах. Версия плагина от второго Февраля `2.8.1`.

**Comment by stavultras** [comment]
Поиск работает, запускается прям из выдачи результатов. Но один фильм не запустился, но я думаю это проблема самого кинопаба.

**Comment by allmazz** [comment]
У меня после ввода названия отображается пустая страница. В чём может быть проблема?

**Comment by quarckster** [comment]
Чтобы разобраться, можно посмотреть kodi.log.

**Comment by stavultras** [comment]
А попробуйте ввести "книга". Я так пробовал, для него точно результаты есть. Может вы как-то не так название вводите.

P.S.: у меня старая версия плагина - 2.5.0, может в ней это работает/не сломано.

**Comment by allmazz** [comment]
kodi.log:
`0:44:06.161 T:140486159730432  NOTICE: [video.kino.pub]: книга
20:44:06.169 T:140486159730432 WARNING: CPythonInvoker(12, /home/cinema/.kodi/addons/video.kino.pub/addon.py): the python script "/home/cinema/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include:
20:44:06.274 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/items?type=movie&title=%D0%BA%D0%BD%D0%B8%D0%B3%D0%B0
20:44:07.421 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=14625
20:44:07.859 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=13345
20:44:08.194 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=22129
20:44:08.647 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=43279
20:44:09.117 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=51601
20:44:09.453 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=4678
20:44:10.023 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=6134
20:44:10.510 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=8236
20:44:10.845 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=15246
20:44:11.248 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=559
20:44:11.633 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=23101
20:44:11.970 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=21916
20:44:12.423 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=6253
20:44:12.725 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=7835
20:44:13.044 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=308
20:44:13.480 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=5954
20:44:13.832 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=17099
20:44:14.352 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=4501
20:44:14.671 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=1235
20:44:14.990 T:140485323773696  NOTICE: [video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=1926
20:44:15.350 T:140485323773696 WARNING: CPythonInvoker(13, /home/cinema/.kodi/addons/video.kino.pub/addon.py): the python script "/home/cinema/.kodi/addons/video.kino.pub/addon.py" has left several classes in memory that we couldn't clean up. The classes include: `

**Comment by allmazz** [comment]
Есть идеи?

**Comment by romannazarenko** [comment]
Поиск работает, только список результатов не на всех скинах показывает. На estuary работает, а на eminence уже нет
