### ISSUE TITLE
Название звуковой дорожки

### ISSUE THREAD

**Issue by Polarnik77** [quarckster/kodi.kino.pub#79]
Coreelec 9.2.1 (kodi 18.5) версия аддона 2.8.1
В аудиодорожках не отображает название.
Например, сериал 2 с половиной человека - три дорожки, на всех написано Unknown. 
При просмотре на сайте отображается наименование перевода (многоголосый нтв
Многоголосый мтв
Оригинал) .

**Comment by quarckster** [comment]
Плагин не може трешить эту проблему. Аудиопоток из кинопаба не содержит метаданныхю
