### ISSUE TITLE
Cтранно работает отметка просмотра.

### ISSUE THREAD

**Issue by apazhe** [quarckster/kodi.kino.pub#8]
Иногда флаг «просмотрено» взводится в самом начале просмотра. Иногда под конец. Иногда не взводится вообще. Иногда его не поставить даже вручную с первого раза, приходится подниматься на уровень выше, потом снова заходить в папку и повторять. 

Какой-то логики в этом поведении я пока не выявил.

**Comment by quarckster** [comment]
Мне кажется в старом аддоне такая же проблема была?

**Comment by quarckster** [comment]
Попробуйте изменить настройки самого Kodi https://kodi.wiki/view/HOW-TO:Modify_automatic_watch_and_resume_points

**Comment by apazhe** [comment]
Я, конечно, попробую. Но во всех остальных местах (DLNA, диск, плагин soap4.me) она работает правильно.

**Comment by apazhe** [comment]
> Мне кажется в старом аддоне такая же проблема была?

Да, ничего не изменилось.

**Comment by olsamurai** [comment]
Этой проблемы не было в старой версии плагина. Настройки в Коди у меня изменены давно. Сейчас ещё раз попробовал - не помогает.

Что происходит:
Включаем в разделе "Я смотрю" следующий эпизод. Смотрим примерно до половины. Останавливаем просмотр. Видим отметку, что сериал начат к просмотру. Нажимаем кнопку назад на пульте. Подымаемся на один уровень вверх. Нажимаем сразу же опять на этом сезоне. Просмтренный до половины эпизод уже помечен как полностью просмотренный. И это можно повторить.

**Comment by olsamurai** [comment]
Специально проверял, ситуация следующая. С фильмами это не происходит. Только с сериалами. Причем в закладках тоже самое наблюдатется. Повторяемость 100%.

**Comment by quarckster** [comment]
Спасибо за наблюдения, попробую разобраться из-за чего это происходит.

**Comment by quarckster** [comment]
@olsamurai @apazhe не могли бы вы протестить баг в этой версии https://github.com/quarckster/kodi.kino.pub/releases/tag/2.1.3

**Comment by apazhe** [comment]
Не раньше вечера воскресенья, увы.

**Comment by olsamurai** [comment]
А я смогу завтра потестить. Всё равно сейчас на больничном.

**Comment by Kampfader** [comment]
вот тестировал я..
у меня сейчас не в Фильмах, не в Сериалах, не работают Флаги..

----------
"флаг для начала Просмотра" 
не ставит всегда, в 5 рас, мошить один рас повезёт
и это невидно по Символу, а при нажатием на Кнопку "C"
----
"флаг «просмотрено» " 
1. Выбираем фильм или Серию..
2. Нажимаем кнопку "C"
3. выберем "Отметить как Просмотренное" либо "Как не Просмотренное"
-- никаких галочек у нас нету
4. Нажимаем кнопку "C"
5. выбираем час "Mark as watched"
и после этого все Галочки появились, либо ушли..

**Comment by quarckster** [comment]
> вот тестировал я.. на Win10 Kodi18b3 64bit
> 
> у меня сейчас не в Фильмах, не в Сериалах, не работают Флаги..
> 
> -"флаг для начала Просмотра"
> 
> не ставит всегда, в 5 рас, мошить один рас повезёт
> и это невидно по Символу, а при нажатием на Кнопку "C"
> 
> -"флаг «просмотрено» "
> 
>     1. Выбираем фильм или Серию..
> 
>     2. Нажимаем кнопку "C"
> 
>     3. выберем "Отметить как Просмотренное" либо "Как не Просмотренное"
>        -- никаких галочек у нас нету
> 
>     4. Нажимаем кнопку "C"
> 
>     5. выбираем "Mark as watched"
>        и после этого все Галочки появились, либо ушли..

Давайте пока разберёмся с версией 17.6. Когда Kodi18 релизнится, тогда и будем работать над портированием.

**Comment by olsamurai** [comment]
Я тестирую на Raspberry Pi II с Kodi 17. Так что всё стандартно.

**Comment by olsamurai** [comment]
К сожалению лучше не стало. Статус "непросмотренный" через контекстное меню поставить нельзя. После недосмотренного эпизода статус после выхода из директории сразу пропадает. Что в закладках, что в "буду смотреть".

**Comment by quarckster** [comment]
@olsamurai не могу воспроизвести баг с контекстным меню, и это, строго говоря, совсем другая ошибка. В изначальном описании речь шла об отметке просмотра после воспроизведения видео.

**Comment by olsamurai** [comment]
quarckster, о контекстном меню я заодно написал. Я понимаю, что проблема другая. Но что мне не даёт покоя, так это то, что в версии 1.6.1 всей этой проблемы со статусом нет...
А вы не можете вообще проблемы со статусом повторить?

**Comment by olsamurai** [comment]
А можно как-то debug для этого REST-интерфейса включить. Я бы посмотрел.

**Comment by quarckster** [comment]
Дело в том, что в этой предрелизной версии, плагин не отправляет никакой информации на сервер о статусе видео. Вот здесь https://github.com/quarckster/kodi.kino.pub/commit/a1fe2ce8dc4e333706620aa05585cc89435f444f#diff-3d24345204b0dc241819199f839cdaaaL295 я удалил этот код.

**Comment by olsamurai** [comment]
Если плагин ничего не отправляет, то при входе в папку он берёт старую информацию с кинопаба. При входе в папку информация должна обновляться (в моем понимании), т.к. сервер единственное место для синхронизации различных приборов (клиентов). А как включить debug только для плагина кинопаба?

**Comment by olsamurai** [comment]
Спасибо, наверное придется разбираться. У меня Коди стоит на Raspberry Pi и она подключена к телеку. И просто так мне никто не даст её отключить (жена и ребенок меня порвут). У меня доступ только по sftp или по SSH.

**Comment by quarckster** [comment]
Коди можно установить на любой комп, аддон можно установить туда же.

**Comment by olsamurai** [comment]
Это понятно, вопрос в том, что будет ли там эта проблема... Завтра буду думать.

**Comment by olsamurai** [comment]
Ситуация цледующая:

1. Контекстное меню - работает! Сам виноват. Плагин добавляет меню пункт на русском (видно в исходниках : Отметить как непросмотренное). Есть еще один пункт от Коди - тоже самое на немецком. Так я автоматически выбирал на немецком. Как результат: ничего не происходило.

2. Проблема с пометкой начато к просмотру.
Я немножко добавил вывовод в лог.  

Выбираю к просмотру "Ходячие мертвецы", 9 сезон, 7 серия.
`10:59:06.893 T:1925876224   DEBUG: OnPlayMedia plugin://video.kino.pub/play?episode_number=7&season_number=9&id=8837&video_data=%7B`
`10:59:07.029 T:1925876224   DEBUG: StartScript - calling plugin kino.pub('plugin://video.kino.pub/play','39','?episode_number=7&season_number=9&id=8837&video_data=%7B%22files%22%3A+%5B%7B%22url%2`

Стартуется плагин:
`10:59:07.030 T:1329586944   DEBUG: CPythonInvoker(49, /home/osmc/.kodi/addons/video.kino.pub/default.py): start processing
10:59:07.050 T:1354752768   DEBUG: Thread scriptobs start, auto delete: false
10:59:07.250 T:1925876224   DEBUG: ------ Window Init (DialogBusy.xml) ------
10:59:07.420 T:1329586944   DEBUG: -->Python Interpreter Initialized<--
10:59:07.420 T:1329586944   DEBUG: CPythonInvoker(49, /home/osmc/.kodi/addons/video.kino.pub/default.py): the source file to load is "/home/osmc/.kodi/addons/video.kino.pub/default.py"
10:59:07.420 T:1329586944   DEBUG: CPythonInvoker(49, /home/osmc/.kodi/addons/video.kino.pub/default.py): setting the Python path to /home/osmc/.kodi/addons/video.kino.pub:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
10:59:07.420 T:1329586944   DEBUG: CPythonInvoker(49, /home/osmc/.kodi/addons/video.kino.pub/default.py): entering source directory /home/osmc/.kodi/addons/video.kino.pub
10:59:07.421 T:1329586944   DEBUG: CPythonInvoker(49, /home/osmc/.kodi/addons/video.kino.pub/default.py): instantiating addon using automatically obtained id of "video.kino.pub" dependent on version 2.1.0 of the xbmc.python api`

И сразу же видим следующий код в логе:
`10:59:08.178 T:1329586944   DEBUG: kinopub GET request: http://api.service-kp.com/v1/watching/marktime?season=9&video=7&id=8837&time=3523
10:59:08.394 T:1329586944   DEBUG: kinopub response: {u'status': 200}`

Т.е. при открытии к просмотру плагин говорит, что он устанавливает marktime!
Причем time=3523, это в секундах продолжительность всего эпизода!
Эпизод уже помечен как просмотрен, хотя еще даже не открыт...

Потом я перематываю на 20 минуту.

`10:59:18.484 T:1354752768   DEBUG: demuxer seek to: 1205007.000000, success`
1205007 в мс примерно 20 минут с секундами. Все совпадает.

Потом просмотр останавливается, но marktime, уже вначале установлен на всю продолжительность эпизода.
Похоже, что проблема в том, что marktime устанавливается в начале, а не там, где остановились!

**Comment by quarckster** [comment]
@olsamurai проверьте, пожалуйста, что в файле `addonworker.py` нет `KinoPubClient("watching/marktime").get()`. Именно эта строчка и делает запрос к `http://api.service-kp.com/v1/watching/marktime?`. В версии 2.1.3 я её как раз и удалил.

**Comment by olsamurai** [comment]
Сразу извините за русский, у меня мнемоническая русская раскладка - это треш и ад.

**Comment by quarckster** [comment]
> Разве не надо какойто callback (event) вида onPlayBackEnded?

Как раз над этим я работаю, api для плагинов предоставляет такую возможность. Что касается статуса "просмотренный", здесь ситуация сложнее. Kodi ставит эту отметку у себя в базе в соотвествии с этими настройками https://kodi.wiki/view/HOW-TO:Modify_automatic_watch_and_resume_points. Однако, в аддоне статус берётся через через api кинопаба. По-хорошему необходимо реализовать коллбэк, который бы отправлял на кинопаб статус о просмотре, когда kodi отмечает видео как просмотренное, но этой возможности в api нет. Поэтому в контекстном меню появились отдельные строчки.

**Comment by olsamurai** [comment]
Тогда все идет по плану ;)
В версии 2.1.3 marktime не ставится, как следствие, после выхода из директории эпизод отмечен как новый (как буд-то и не начинали смотреть)
Бага нет, все в соответствии скодом работает!
