### ISSUE TITLE
Проблема с воспроизведением контента.

### ISSUE THREAD

**Issue by user-is-absinthe** [quarckster/kodi.kino.pub#81]
Привет!
Я установил последнюю версию твоего дополнения, подключил к аккаунту при помощи сайта, но не могу посмотреть что-либо. А именно, я могу получить информацию об аккаунте, получить список, например, новинок (но не быстро), но при выборе конкретного фильма и попытке просмотра - шестеренка крутится, крутится и... Ничего.
Сетап:
- RPi 3B+
- Raspbian 10 Buster
- Kodi 18.6
- Kodi.kino.pub 2.8.1

Что делал и что не помогло: переключал VPN, игрался с настройками на сайте, перезаходил в плагин. (Там есть кнопка выхода? Я удалял и ставил заново, но не уверен, что это точно работает.)
Глянул лог - висит ошибка аутентификации.

Так же, из странного, при привязке устройства к аккаунту мне предлагается два кода привязки. В первый раз я использовал первый, во второй - второй. Но видимый результат тот же (в первый раз лог не смотрел).

[kodi.log](https://github.com/quarckster/kodi.kino.pub/files/4455167/kodi.log)

**Comment by user-is-absinthe** [comment]
При откате на 2.8.0 получил другую ошибку.
[kodi_280.log](https://github.com/quarckster/kodi.kino.pub/files/4455244/kodi_280.log)
"Двойного" кода не было.
2.8.0.beta1 - аналогично.
И такое же поведение на последней версии сейчас.
[kodi_281.log](https://github.com/quarckster/kodi.kino.pub/files/4455382/kodi_281.log)
Первую ошибку воспроизвести не удалось.

**Comment by quarckster** [comment]
"Другую" ошибку исправил в https://github.com/quarckster/kodi.kino.pub/commit/b99694e0eca2dbe9e1e86999f6167c4767771078
