### ISSUE TITLE
Не показываются списки фильмов и сериалов

### ISSUE THREAD

**Issue by kolnogorov** [quarckster/kodi.kino.pub#83]
Сетап:
Raspberry Pi 3
Kodi 17.4
Kodi.kino.pub 2.8.1

Всё работает, авторизовался, плагин запускается. Но невозможно получить список фильмов, сериалов и всего прочего. Когда заходишь в любую папку - просто показывается пустой экран:

![image](https://user-images.githubusercontent.com/8288103/80602480-dcc5b400-8a37-11ea-8cfd-166a31f71abd.png)

Закладки тоже не работают, там пусто.

Единственное, как можно что-либо посмотреть - это добавить сериал в раздел "Я смотрю" - там они отображаются. И больше нигде.

Переустанавливал плагин, перепривязывал устройство, пробовал поменять сервера и протоколы - результат один.

**Comment by quarckster** [comment]
Приложите kodi.log

**Comment by kolnogorov** [comment]
А подскажите, как его получить? Не могу найти

Я попробовал откатиться до версии 2.7.1 и всё заработало.
На 2.8.0 тоже не работает.

**Comment by quarckster** [comment]
https://kodi.wiki/view/Log_file/Advanced

**Comment by greenpeas** [comment]
2.8.2 тоже не грузит списки.
Показал только то, что не досмотрел.

**Comment by quarckster** [comment]
Не могу воспроизвести. Установил плагин на свежий kodi 18.6, активировал, все пункты меню отображаются, содержимое тоже. Без логов ничем помочь не могу.
