### ISSUE TITLE
Буферизация увеличение

### ISSUE THREAD

**Issue by buyfishya** [quarckster/kodi.kino.pub#84]
Давно пользуюсь плагином на LibreElec. В последнее время при просмотре часто фризиться видео, ждешь когда оно догрузится и так постоянно, каждую минуту происходит зависон на 1-2 секунды. Нет никакой настройки чтобы буфер можно увеличить для плагина для просматриваемого фильма?

**Comment by quarckster** [comment]
Плагин не отвечает за воспроизведение, он только вытаскивает ссылку из API и передаёт Kodi. В качестве оптимизации я бы порекомендовал установить inputstream.adaptive и включить его поддержку в настройках плагина:
https://github.com/peak3d/inputstream.adaptive
https://kodi.wiki/view/Add-on:InputStream_Adaptive

**Comment by apazhe** [comment]
Буферизацией потоков занимается сама KODI, её и нужно настраивать.

Я отдал два гига под это дело и рад.
