### ISSUE TITLE
Ошибка избранного

### ISSUE THREAD

**Issue by GhostR111der** [quarckster/kodi.kino.pub#86]
Приветствую!
Использую последнюю версию плагина 2.8.2 на Raspberry Pi 3 с OSMC
Раньше когда добавлял что-то из kinopub в избранное OSMC потом спокойно открывал это оттуда. Сейчас же когда добавляю сериал или фильм, при попытке открыть выдает ошибку. В версии 2.7.1 например или 1.2.1 такой проблемы нет

**Comment by Limeone** [comment]
Не уверен на 100%, но по-моему падает [здесь](https://github.com/quarckster/kodi.kino.pub/blob/b99694e0eca2dbe9e1e86999f6167c4767771078/src/resources/lib/main.py#L400).

**Comment by Limeone** [comment]
@quarckster Делал workaround у себя в форке, могу сделать PL на ревью, вдруг подойдет))

**Comment by quarckster** [comment]
Разделяю подозрения. Видимо проблема в том, что данные, которые мы храним глобальном объекте Window доступны только во время навигации по плагину. Если по урлу напрямую перейти, что происходит в Избранном, то этих данных нет.

**Comment by Limeone** [comment]
> Разделяю подозрения. Видимо проблема в том, что данные, которые мы храним глобальном объекте Window, доступны только во время навигации по плагину. Если по урлу напрямую перейти, что происходит в Избранном, то этих данных нет.

Да, именно так

**Comment by Limeone** [comment]
Можно сделать чтоб плагин снова шел в апи за данными если `get_window_property` ничего не нашел.

**Comment by quarckster** [comment]
Да, это первое, что на ум приходит.
