### ISSUE TITLE
Хотелка: Добавление в библиотеку Коди

### ISSUE THREAD

**Issue by LordMerlin** [quarckster/kodi.kino.pub#87]
Прошу рассмотреть возможность сделать функционал, позволяющий добавлять сериалы и фильмы в библиотеку Коди.
По типу как это сделано например в Элементум. 
При добавлении в папку настроенную по умолчанию для сериалов или фильмов создать подпапку с названием и годом, а в ней strm файлы с номерами серий, в случае сериала, с ссылкой в каждом на свой файл сериала на сервере, прямые, если токены в ссылках не протухают, или ссылку через вызов аддона, если они динамические.

**Comment by quarckster** [comment]
Я в этой фиче не заинтересован, но с удовольствием приму патч, добавляющий этот функционал.

**Comment by LordMerlin** [comment]
Спасибо за быстрый ответ. Жаль что он отрицательный.
Фича то замечательная.
Как тогда удобно можно следить за выходом новых серий определенных сериалов?
В андроид приложении такое есть?

**Comment by fallenfuzz** [comment]
> Спасибо за быстрый ответ. Жаль что он отрицательный.
> Фича то замечательная.
> Как тогда удобно можно следить за выходом новых серий определенных сериалов?
> В андроид приложении такое есть?

Есть раздел "я смотрю" если все серии просмотренны, исчезает из списка, как только появляетса новая серия, сериал возвращается в список.
Помимо на можно выбрать сообшения на почту и все обновления, фильмы, сериалы, новые серии приходять на мыло.

**Comment by LordMerlin** [comment]
Спасибо. Буду пробовать приспособиться.
Беда в том, что в зале и в спальне я и дочь смотрим иногда одни и те же сериалы раздельно, но разный прогресс по ним.
Локальная база Коди отлично такую проблему решает.

**Comment by Limeone** [comment]
Реализовывал у себя в форке такую фичу экспериментально. Из-за синхронизации просмотров в самом кинопабе и библиотеке, обновления добавление новых серий в сериалах, синхронизации  и обновленения фильмов когда объединяют фильмы с разными звуковыми дорожками в один и т.д. очень усложняется плагин. Пользоваться фичей будут далеко не все, а стабильность плагина упадет, ИМХО.
