### ISSUE TITLE
Нет отображения обложек 

### ISSUE THREAD

**Issue by dimetrius-zx** [quarckster/kodi.kino.pub#88]
Доброго времени суток на крайней версии аддона 2.8.2. В Kodi 18.7 в обложке Aeon nox silvo 7.0.9  не отображается обложки к фильмам , подскажите как исправить . Заранее спасибо.
![screenshot001](https://user-images.githubusercontent.com/64330264/84888076-67717980-b09f-11ea-880e-1f2ada5f8c8f.png)

**Comment by quarckster** [comment]
Поддерживается только скин по умолчанию

**Comment by dimetrius-zx** [comment]
Попробывал  версию 2.7.1 тут отображения обложек работает , но нет выбора контента 4К.
Спасибо за быстрый ответ , хотелось бы в будущем надеяться что в этом скине заработает отображения обложек
