### ISSUE TITLE
Странные ошибки - kodi.log

### ISSUE THREAD

**Issue by Lontron** [quarckster/kodi.kino.pub#91]
В kodi.log показывает очень странные ошибки, например, когда я открываю раздел  Горячие или любой раздел в kodi.log показывает странные ошибки, все эти вещи открываются нормально, только в kodi.log показывает странные ошибки.

[video.kino.pub]: sending GET request to https://api.service-kp.com/v1/watching?id=64009
2020-06-23 16:35:58.630 T:3563057984   ERROR: NEWADDON Unknown Video Info Key "time"

Log: https://pastebin.com/1Ejx0Eum

**Comment by quarckster** [comment]
Это ошибка не влияет на работу плагина, но ключ "time" используется.
