### ISSUE TITLE
Не работает в режиме 4K hls, hls2, hls4

### ISSUE THREAD

**Issue by Lontron** [quarckster/kodi.kino.pub#94]
Не работает в режиме 4K hls, hls2, hls4, http работает, в режиме full hd (1080p) работают все форматы. Вы можете проверить это. Спасибо

**Comment by quarckster** [comment]
Что не работает? Пожалуйста предоставьте конкретные шаги для воспроизведния ошибки и логи.

**Comment by Lontron** [comment]
Поток просто не открывается вообще, иногда коди слетает/crash. 

Log: http://paste.kodi.tv/mozoyojopi 

ERROR: OpenDemuxStream - Error creating demuxer

**Comment by quarckster** [comment]
Плагин ни при чём, что с коди или с сервисом. Плагин не занимается вопроизведением, а только передаёт ссылку плееру коди. Проверьте, что у вас настроен inpustream.adaptive https://github.com/peak3d/inputstream.adaptive

**Comment by Lontron** [comment]
Inputstream adaptive включен, нужно сделать какие-либо настройки?
