### ISSUE TITLE
Хотелка: Добавления Репозиторий для автообновления

### ISSUE THREAD

**Issue by Lontron** [quarckster/kodi.kino.pub#96]
Добавления Репозиторий для автообновления KinoPub. 
Каждый раз не удобно скачивать, ставить на флешку и заново устанавливать, проще через репозиторий и таких проблем не возникает.

**Comment by Lontron** [comment]
https://github.com/drinfernoo/repository.example Пример как создать.

**Comment by Lontron** [comment]
@quarckster Работает KinoPub HDR с inputstream adaptive?

**Comment by Lontron** [comment]
@quarckster ?

**Comment by Lontron** [comment]
@quarckster можешь мне ответить?

**Comment by Lontron** [comment]
Как будто я разговариваю со стенами :)

**Comment by quarckster** [comment]
Я не знаю, что такое kinopub hdr, в настройках такого нет. Этот вопрос к данному issue отншения не имеет.
